#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionRespawned

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameModule_structs.hpp"
#include "InGameModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionRespawned.BP_ActionRespawned_C
// 0x0030 (0x01E0 - 0x01B0)
class UBP_ActionRespawned_C final : public UActionNormalBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FTransitionMaterialScalarParamArgment  argment;                                           // 0x01B8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          bEnableShiftAction;                                // 0x01D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_ActionRespawned(int32 EntryPoint);
	void CancelEvent();
	void MaterialControl();
	void BP_OnEndAction(const class FName& nextAction);
	void BP_ActionRemote();
	void BP_ActionMain();
	void BP_OnBeginAction(const class FName& prevAction);

	bool BP_IsEnableShiftAction(const class FName& nextAction) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionRespawned_C">();
	}
	static class UBP_ActionRespawned_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionRespawned_C>();
	}
};
static_assert(alignof(UBP_ActionRespawned_C) == 0x000008, "Wrong alignment on UBP_ActionRespawned_C");
static_assert(sizeof(UBP_ActionRespawned_C) == 0x0001E0, "Wrong size on UBP_ActionRespawned_C");
static_assert(offsetof(UBP_ActionRespawned_C, UberGraphFrame) == 0x0001B0, "Member 'UBP_ActionRespawned_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_ActionRespawned_C, argment) == 0x0001B8, "Member 'UBP_ActionRespawned_C::argment' has a wrong offset!");
static_assert(offsetof(UBP_ActionRespawned_C, bEnableShiftAction) == 0x0001D8, "Member 'UBP_ActionRespawned_C::bEnableShiftAction' has a wrong offset!");

}

