#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionRun

#include "Basic.hpp"

#include "BP_ActionRun_classes.hpp"
#include "BP_ActionRun_parameters.hpp"


namespace SDK
{

// Function BP_ActionRun.BP_ActionRun_C.ExecuteUbergraph_BP_ActionRun
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionRun_C::ExecuteUbergraph_BP_ActionRun(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRun_C", "ExecuteUbergraph_BP_ActionRun");

	Params::BP_ActionRun_C_ExecuteUbergraph_BP_ActionRun Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionRun.BP_ActionRun_C.BP_OnEndAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionRun_C::BP_OnEndAction(const class FName& nextAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRun_C", "BP_OnEndAction");

	Params::BP_ActionRun_C_BP_OnEndAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionRun.BP_ActionRun_C.BP_OnEndAimingMode
// (Event, Protected, BlueprintEvent)

void UBP_ActionRun_C::BP_OnEndAimingMode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRun_C", "BP_OnEndAimingMode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRun.BP_ActionRun_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionRun_C::BP_OnBeginAction(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRun_C", "BP_OnBeginAction");

	Params::BP_ActionRun_C_BP_OnBeginAction Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionRun.BP_ActionRun_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_ActionRun_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRun_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRun.BP_ActionRun_C.UpdateMoveDirection
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionRun_C::UpdateMoveDirection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRun_C", "UpdateMoveDirection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRun.BP_ActionRun_C.UpdateCharacterDirection
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionRun_C::UpdateCharacterDirection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRun_C", "UpdateCharacterDirection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRun.BP_ActionRun_C.UpdateSpeedRate
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionRun_C::UpdateSpeedRate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRun_C", "UpdateSpeedRate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRun.BP_ActionRun_C.GetSpeed
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  _Action_Run_Initial_Speed                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  _Action_Run_Last_Speed                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  _Action_Run_Accel_Span                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionRun_C::GetSpeed(float* _Action_Run_Initial_Speed, float* _Action_Run_Last_Speed, float* _Action_Run_Accel_Span)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRun_C", "GetSpeed");

	Params::BP_ActionRun_C_GetSpeed Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (_Action_Run_Initial_Speed != nullptr)
		*_Action_Run_Initial_Speed = Parms._Action_Run_Initial_Speed;

	if (_Action_Run_Last_Speed != nullptr)
		*_Action_Run_Last_Speed = Parms._Action_Run_Last_Speed;

	if (_Action_Run_Accel_Span != nullptr)
		*_Action_Run_Accel_Span = Parms._Action_Run_Accel_Span;
}


// Function BP_ActionRun.BP_ActionRun_C.GetAccelSpan
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  _Action_Run_Initial_Turn_Span                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionRun_C::GetAccelSpan(float* _Action_Run_Initial_Turn_Span)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRun_C", "GetAccelSpan");

	Params::BP_ActionRun_C_GetAccelSpan Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (_Action_Run_Initial_Turn_Span != nullptr)
		*_Action_Run_Initial_Turn_Span = Parms._Action_Run_Initial_Turn_Span;
}


// Function BP_ActionRun.BP_ActionRun_C.BP_IsEnableShiftAction
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UBP_ActionRun_C::BP_IsEnableShiftAction(const class FName& nextAction) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRun_C", "BP_IsEnableShiftAction");

	Params::BP_ActionRun_C_BP_IsEnableShiftAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

