#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionAirJumpBeginForward

#include "Basic.hpp"

#include "BP_ActionAirJumpBeginForward_classes.hpp"
#include "BP_ActionAirJumpBeginForward_parameters.hpp"


namespace SDK
{

// Function BP_ActionAirJumpBeginForward.BP_ActionAirJumpBeginForward_C.ExecuteUbergraph_BP_ActionAirJumpBeginForward
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAirJumpBeginForward_C::ExecuteUbergraph_BP_ActionAirJumpBeginForward(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAirJumpBeginForward_C", "ExecuteUbergraph_BP_ActionAirJumpBeginForward");

	Params::BP_ActionAirJumpBeginForward_C_ExecuteUbergraph_BP_ActionAirJumpBeginForward Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAirJumpBeginForward.BP_ActionAirJumpBeginForward_C.BP_OnEndAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAirJumpBeginForward_C::BP_OnEndAction(const class FName& nextAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAirJumpBeginForward_C", "BP_OnEndAction");

	Params::BP_ActionAirJumpBeginForward_C_BP_OnEndAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAirJumpBeginForward.BP_ActionAirJumpBeginForward_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_ActionAirJumpBeginForward_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAirJumpBeginForward_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionAirJumpBeginForward.BP_ActionAirJumpBeginForward_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAirJumpBeginForward_C::BP_OnBeginAction(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAirJumpBeginForward_C", "BP_OnBeginAction");

	Params::BP_ActionAirJumpBeginForward_C_BP_OnBeginAction Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}

}

