#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionDamageGuardStrong

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InGameModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionDamageGuardStrong.BP_ActionDamageGuardStrong_C
// 0x0010 (0x01C8 - 0x01B8)
class UBP_ActionDamageGuardStrong_C final : public UActionDamageBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          LandingOK;                                         // 0x01C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          landing;                                           // 0x01C1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_ActionDamageGuardStrong(int32 EntryPoint);
	void BP_OnLandingEvent();
	void BP_OnEndAction(const class FName& nextAction);
	void BP_ActionRemote();
	void BP_OnBeginAction(const class FName& prevAction);
	void BP_ActionMain();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionDamageGuardStrong_C">();
	}
	static class UBP_ActionDamageGuardStrong_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionDamageGuardStrong_C>();
	}
};
static_assert(alignof(UBP_ActionDamageGuardStrong_C) == 0x000008, "Wrong alignment on UBP_ActionDamageGuardStrong_C");
static_assert(sizeof(UBP_ActionDamageGuardStrong_C) == 0x0001C8, "Wrong size on UBP_ActionDamageGuardStrong_C");
static_assert(offsetof(UBP_ActionDamageGuardStrong_C, UberGraphFrame) == 0x0001B8, "Member 'UBP_ActionDamageGuardStrong_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_ActionDamageGuardStrong_C, LandingOK) == 0x0001C0, "Member 'UBP_ActionDamageGuardStrong_C::LandingOK' has a wrong offset!");
static_assert(offsetof(UBP_ActionDamageGuardStrong_C, landing) == 0x0001C1, "Member 'UBP_ActionDamageGuardStrong_C::landing' has a wrong offset!");

}

