#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionDashLand

#include "Basic.hpp"

#include "BP_ActionDashLand_classes.hpp"
#include "BP_ActionDashLand_parameters.hpp"


namespace SDK
{

// Function BP_ActionDashLand.BP_ActionDashLand_C.ExecuteUbergraph_BP_ActionDashLand
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionDashLand_C::ExecuteUbergraph_BP_ActionDashLand(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDashLand_C", "ExecuteUbergraph_BP_ActionDashLand");

	Params::BP_ActionDashLand_C_ExecuteUbergraph_BP_ActionDashLand Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionDashLand.BP_ActionDashLand_C.BP_ActionRemote
// (Event, Protected, BlueprintEvent)

void UBP_ActionDashLand_C::BP_ActionRemote()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDashLand_C", "BP_ActionRemote");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionDashLand.BP_ActionDashLand_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionDashLand_C::BP_OnBeginAction(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDashLand_C", "BP_OnBeginAction");

	Params::BP_ActionDashLand_C_BP_OnBeginAction Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionDashLand.BP_ActionDashLand_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_ActionDashLand_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDashLand_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}

}

