#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionDashBegin

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InGameModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionDashBegin.BP_ActionDashBegin_C
// 0x0008 (0x01B8 - 0x01B0)
class UBP_ActionDashBegin_C final : public UActionNormalBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ActionDashBegin(int32 EntryPoint);
	void BP_OnLeaveGroundEvent();
	void Ground_Check();
	void BP_OnBeginAimingMode();
	void BP_OnEndAction(const class FName& nextAction);
	void BP_OnBeginAction(const class FName& prevAction);
	void BP_ActionMain();
	void UpdateMoveDirection();
	void UpdateCharacterDirection();
	void UpdateSpeedRate();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionDashBegin_C">();
	}
	static class UBP_ActionDashBegin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionDashBegin_C>();
	}
};
static_assert(alignof(UBP_ActionDashBegin_C) == 0x000008, "Wrong alignment on UBP_ActionDashBegin_C");
static_assert(sizeof(UBP_ActionDashBegin_C) == 0x0001B8, "Wrong size on UBP_ActionDashBegin_C");
static_assert(offsetof(UBP_ActionDashBegin_C, UberGraphFrame) == 0x0001B0, "Member 'UBP_ActionDashBegin_C::UberGraphFrame' has a wrong offset!");

}

