#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionDyingMove

#include "Basic.hpp"

#include "BP_ActionDyingMove_classes.hpp"
#include "BP_ActionDyingMove_parameters.hpp"


namespace SDK
{

// Function BP_ActionDyingMove.BP_ActionDyingMove_C.ExecuteUbergraph_BP_ActionDyingMove
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionDyingMove_C::ExecuteUbergraph_BP_ActionDyingMove(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDyingMove_C", "ExecuteUbergraph_BP_ActionDyingMove");

	Params::BP_ActionDyingMove_C_ExecuteUbergraph_BP_ActionDyingMove Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionDyingMove.BP_ActionDyingMove_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_ActionDyingMove_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDyingMove_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionDyingMove.BP_ActionDyingMove_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionDyingMove_C::BP_OnBeginAction(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDyingMove_C", "BP_OnBeginAction");

	Params::BP_ActionDyingMove_C_BP_OnBeginAction Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionDyingMove.BP_ActionDyingMove_C.BP_OnEndAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionDyingMove_C::BP_OnEndAction(const class FName& nextAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDyingMove_C", "BP_OnEndAction");

	Params::BP_ActionDyingMove_C_BP_OnEndAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionDyingMove.BP_ActionDyingMove_C.UpdateMoveDirection
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionDyingMove_C::UpdateMoveDirection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDyingMove_C", "UpdateMoveDirection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionDyingMove.BP_ActionDyingMove_C.UpdateSpeedRate
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionDyingMove_C::UpdateSpeedRate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDyingMove_C", "UpdateSpeedRate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionDyingMove.BP_ActionDyingMove_C.UpdateCharacterDirection
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionDyingMove_C::UpdateCharacterDirection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDyingMove_C", "UpdateCharacterDirection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionDyingMove.BP_ActionDyingMove_C.BP_IsEnableShiftAction
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UBP_ActionDyingMove_C::BP_IsEnableShiftAction(const class FName& nextAction) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDyingMove_C", "BP_IsEnableShiftAction");

	Params::BP_ActionDyingMove_C_BP_IsEnableShiftAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

