#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionSuperJumpRise

#include "Basic.hpp"

#include "BP_ActionSuperJumpRise_classes.hpp"
#include "BP_ActionSuperJumpRise_parameters.hpp"


namespace SDK
{

// Function BP_ActionSuperJumpRise.BP_ActionSuperJumpRise_C.ExecuteUbergraph_BP_ActionSuperJumpRise
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionSuperJumpRise_C::ExecuteUbergraph_BP_ActionSuperJumpRise(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpRise_C", "ExecuteUbergraph_BP_ActionSuperJumpRise");

	Params::BP_ActionSuperJumpRise_C_ExecuteUbergraph_BP_ActionSuperJumpRise Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionSuperJumpRise.BP_ActionSuperJumpRise_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_ActionSuperJumpRise_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpRise_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionSuperJumpRise.BP_ActionSuperJumpRise_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionSuperJumpRise_C::BP_OnBeginAction(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpRise_C", "BP_OnBeginAction");

	Params::BP_ActionSuperJumpRise_C_BP_OnBeginAction Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionSuperJumpRise.BP_ActionSuperJumpRise_C.UpdateCo-Routine
// (BlueprintCallable, BlueprintEvent)

void UBP_ActionSuperJumpRise_C::UpdateCo_Routine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpRise_C", "UpdateCo-Routine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionSuperJumpRise.BP_ActionSuperJumpRise_C.BP_OnEndAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionSuperJumpRise_C::BP_OnEndAction(const class FName& nextAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpRise_C", "BP_OnEndAction");

	Params::BP_ActionSuperJumpRise_C_BP_OnEndAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionSuperJumpRise.BP_ActionSuperJumpRise_C.CalcSpeedH
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Initial_Speed                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  Last_Speed                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  Accel_Span                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionSuperJumpRise_C::CalcSpeedH(float* Initial_Speed, float* Last_Speed, float* Accel_Span)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpRise_C", "CalcSpeedH");

	Params::BP_ActionSuperJumpRise_C_CalcSpeedH Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Initial_Speed != nullptr)
		*Initial_Speed = Parms.Initial_Speed;

	if (Last_Speed != nullptr)
		*Last_Speed = Parms.Last_Speed;

	if (Accel_Span != nullptr)
		*Accel_Span = Parms.Accel_Span;
}


// Function BP_ActionSuperJumpRise.BP_ActionSuperJumpRise_C.CalcJumpParam
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Speed                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  span                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionSuperJumpRise_C::CalcJumpParam(float* Speed, float* span)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpRise_C", "CalcJumpParam");

	Params::BP_ActionSuperJumpRise_C_CalcJumpParam Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Speed != nullptr)
		*Speed = Parms.Speed;

	if (span != nullptr)
		*span = Parms.span;
}


// Function BP_ActionSuperJumpRise.BP_ActionSuperJumpRise_C.BP_IsEnableShiftAction
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UBP_ActionSuperJumpRise_C::BP_IsEnableShiftAction(const class FName& nextAction) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionSuperJumpRise_C", "BP_IsEnableShiftAction");

	Params::BP_ActionSuperJumpRise_C_BP_IsEnableShiftAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

