#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionCrouchEnd

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InGameModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionCrouchEnd.BP_ActionCrouchEnd_C
// 0x0008 (0x01B8 - 0x01B0)
class UBP_ActionCrouchEnd_C final : public UActionNormalBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ActionCrouchEnd(int32 EntryPoint);
	void BP_OnEndAction(const class FName& nextAction);
	void BP_ActionMain();
	void BP_OnBeginAction(const class FName& prevAction);
	void UpdateMoveDirection();
	void UpdateSpeedRate();
	void UpdateCharacterDirection();

	bool BP_IsEnableShiftAction(const class FName& nextAction) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionCrouchEnd_C">();
	}
	static class UBP_ActionCrouchEnd_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionCrouchEnd_C>();
	}
};
static_assert(alignof(UBP_ActionCrouchEnd_C) == 0x000008, "Wrong alignment on UBP_ActionCrouchEnd_C");
static_assert(sizeof(UBP_ActionCrouchEnd_C) == 0x0001B8, "Wrong size on UBP_ActionCrouchEnd_C");
static_assert(offsetof(UBP_ActionCrouchEnd_C, UberGraphFrame) == 0x0001B0, "Member 'UBP_ActionCrouchEnd_C::UberGraphFrame' has a wrong offset!");

}

