#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionAirJumpBegin

#include "Basic.hpp"

#include "BP_ActionAirJumpBegin_classes.hpp"
#include "BP_ActionAirJumpBegin_parameters.hpp"


namespace SDK
{

// Function BP_ActionAirJumpBegin.BP_ActionAirJumpBegin_C.ExecuteUbergraph_BP_ActionAirJumpBegin
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAirJumpBegin_C::ExecuteUbergraph_BP_ActionAirJumpBegin(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAirJumpBegin_C", "ExecuteUbergraph_BP_ActionAirJumpBegin");

	Params::BP_ActionAirJumpBegin_C_ExecuteUbergraph_BP_ActionAirJumpBegin Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAirJumpBegin.BP_ActionAirJumpBegin_C.BP_OnEndAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAirJumpBegin_C::BP_OnEndAction(const class FName& nextAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAirJumpBegin_C", "BP_OnEndAction");

	Params::BP_ActionAirJumpBegin_C_BP_OnEndAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAirJumpBegin.BP_ActionAirJumpBegin_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionAirJumpBegin_C::BP_OnBeginAction(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAirJumpBegin_C", "BP_OnBeginAction");

	Params::BP_ActionAirJumpBegin_C_BP_OnBeginAction Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionAirJumpBegin.BP_ActionAirJumpBegin_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_ActionAirJumpBegin_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAirJumpBegin_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionAirJumpBegin.BP_ActionAirJumpBegin_C.GetBrakeSpan
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UBP_ActionAirJumpBegin_C::GetBrakeSpan()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionAirJumpBegin_C", "GetBrakeSpan");

	Params::BP_ActionAirJumpBegin_C_GetBrakeSpan Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

