#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionDamageKnockDown

#include "Basic.hpp"

#include "BP_ActionDamageKnockDown_classes.hpp"
#include "BP_ActionDamageKnockDown_parameters.hpp"


namespace SDK
{

// Function BP_ActionDamageKnockDown.BP_ActionDamageKnockDown_C.ExecuteUbergraph_BP_ActionDamageKnockDown
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionDamageKnockDown_C::ExecuteUbergraph_BP_ActionDamageKnockDown(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDamageKnockDown_C", "ExecuteUbergraph_BP_ActionDamageKnockDown");

	Params::BP_ActionDamageKnockDown_C_ExecuteUbergraph_BP_ActionDamageKnockDown Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionDamageKnockDown.BP_ActionDamageKnockDown_C.BP_ActionRemote
// (Event, Protected, BlueprintEvent)

void UBP_ActionDamageKnockDown_C::BP_ActionRemote()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDamageKnockDown_C", "BP_ActionRemote");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionDamageKnockDown.BP_ActionDamageKnockDown_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionDamageKnockDown_C::BP_OnBeginAction(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDamageKnockDown_C", "BP_OnBeginAction");

	Params::BP_ActionDamageKnockDown_C_BP_OnBeginAction Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionDamageKnockDown.BP_ActionDamageKnockDown_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_ActionDamageKnockDown_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDamageKnockDown_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionDamageKnockDown.BP_ActionDamageKnockDown_C.UpdateOnce
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionDamageKnockDown_C::UpdateOnce()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDamageKnockDown_C", "UpdateOnce");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionDamageKnockDown.BP_ActionDamageKnockDown_C.SetDamageAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionDamageKnockDown_C::SetDamageAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDamageKnockDown_C", "SetDamageAnimation");

	UObject::ProcessEvent(Func, nullptr);
}

}

