#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionHover

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InGameModule_classes.hpp"
#include "CommonModule_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionHover.BP_ActionHover_C
// 0x0018 (0x01C8 - 0x01B0)
class UBP_ActionHover_C final : public UActionNormalBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         totalDelta;                                        // 0x01B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         deltaMultipli;                                     // 0x01BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         upDownSpeedMultipli;                               // 0x01C0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ActionHover(int32 EntryPoint);
	void BP_OnEndAction(const class FName& nextAction);
	void BP_OnLandingEvent();
	void BP_ActionMain();
	void BP_OnBeginAction(const class FName& prevAction);
	void InitMovement();
	void MainMovement();
	void UpdateMoveDirection();
	void UpdateCharacterDirection();
	void UpdateMoveSpeed();
	void UpdateLocation();

	bool BP_IsEnableShiftAction(const class FName& nextAction) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionHover_C">();
	}
	static class UBP_ActionHover_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionHover_C>();
	}
};
static_assert(alignof(UBP_ActionHover_C) == 0x000008, "Wrong alignment on UBP_ActionHover_C");
static_assert(sizeof(UBP_ActionHover_C) == 0x0001C8, "Wrong size on UBP_ActionHover_C");
static_assert(offsetof(UBP_ActionHover_C, UberGraphFrame) == 0x0001B0, "Member 'UBP_ActionHover_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_ActionHover_C, totalDelta) == 0x0001B8, "Member 'UBP_ActionHover_C::totalDelta' has a wrong offset!");
static_assert(offsetof(UBP_ActionHover_C, deltaMultipli) == 0x0001BC, "Member 'UBP_ActionHover_C::deltaMultipli' has a wrong offset!");
static_assert(offsetof(UBP_ActionHover_C, upDownSpeedMultipli) == 0x0001C0, "Member 'UBP_ActionHover_C::upDownSpeedMultipli' has a wrong offset!");

}

