#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionDamage

#include "Basic.hpp"

#include "BP_ActionDamage_classes.hpp"
#include "BP_ActionDamage_parameters.hpp"


namespace SDK
{

// Function BP_ActionDamage.BP_ActionDamage_C.ExecuteUbergraph_BP_ActionDamage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionDamage_C::ExecuteUbergraph_BP_ActionDamage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDamage_C", "ExecuteUbergraph_BP_ActionDamage");

	Params::BP_ActionDamage_C_ExecuteUbergraph_BP_ActionDamage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionDamage.BP_ActionDamage_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionDamage_C::BP_OnBeginAction(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDamage_C", "BP_OnBeginAction");

	Params::BP_ActionDamage_C_BP_OnBeginAction Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionDamage.BP_ActionDamage_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_ActionDamage_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDamage_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionDamage.BP_ActionDamage_C.UpdateOnce
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionDamage_C::UpdateOnce()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDamage_C", "UpdateOnce");

	UObject::ProcessEvent(Func, nullptr);
}

}

