#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionRecoverAlly

#include "Basic.hpp"

#include "BP_ActionRecoverAlly_classes.hpp"
#include "BP_ActionRecoverAlly_parameters.hpp"


namespace SDK
{

// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.ExecuteUbergraph_BP_ActionRecoverAlly
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionRecoverAlly_C::ExecuteUbergraph_BP_ActionRecoverAlly(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "ExecuteUbergraph_BP_ActionRecoverAlly");

	Params::BP_ActionRecoverAlly_C_ExecuteUbergraph_BP_ActionRecoverAlly Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.BP_OnEndAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionRecoverAlly_C::BP_OnEndAction(const class FName& nextAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "BP_OnEndAction");

	Params::BP_ActionRecoverAlly_C_BP_OnEndAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.Negotiate Complete
// (BlueprintCallable, BlueprintEvent)

void UBP_ActionRecoverAlly_C::Negotiate_Complete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "Negotiate Complete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.BP_ActionRemote
// (Event, Protected, BlueprintEvent)

void UBP_ActionRecoverAlly_C::BP_ActionRemote()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "BP_ActionRemote");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.BP_ActionMain
// (Event, Protected, BlueprintEvent)

void UBP_ActionRecoverAlly_C::BP_ActionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "BP_ActionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.BP_OnBeginAction
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      prevAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionRecoverAlly_C::BP_OnBeginAction(const class FName& prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "BP_OnBeginAction");

	Params::BP_ActionRecoverAlly_C_BP_OnBeginAction Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             prevAction                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionRecoverAlly_C::Initialize(class FName prevAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "Initialize");

	Params::BP_ActionRecoverAlly_C_Initialize Parms{};

	Parms.prevAction = prevAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.Turning
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float*                                  TurnSpan                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ActionRecoverAlly_C::Turning(float* TurnSpan)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "Turning");

	Params::BP_ActionRecoverAlly_C_Turning Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TurnSpan != nullptr)
		*TurnSpan = Parms.TurnSpan;
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.Begin
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionRecoverAlly_C::Begin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "Begin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.Recover
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionRecoverAlly_C::Recover()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "Recover");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.Complete
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionRecoverAlly_C::Complete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "Complete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.SetInteractedTarget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Interacted                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ActionRecoverAlly_C::SetInteractedTarget(bool Interacted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "SetInteractedTarget");

	Params::BP_ActionRecoverAlly_C_SetInteractedTarget Parms{};

	Parms.Interacted = Interacted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.BeginFaceTurn
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionRecoverAlly_C::BeginFaceTurn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "BeginFaceTurn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.EndFaceTurn
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ActionRecoverAlly_C::EndFaceTurn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "EndFaceTurn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ActionRecoverAlly.BP_ActionRecoverAlly_C.BP_IsEnableShiftAction
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const class FName&                      nextAction                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UBP_ActionRecoverAlly_C::BP_IsEnableShiftAction(const class FName& nextAction) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionRecoverAlly_C", "BP_IsEnableShiftAction");

	Params::BP_ActionRecoverAlly_C_BP_IsEnableShiftAction Parms{};

	Parms.nextAction = nextAction;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

