#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionAttack_PickUpItem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InGameModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionAttack_PickUpItem.BP_ActionAttack_PickUpItem_C
// 0x0008 (0x03D8 - 0x03D0)
class UBP_ActionAttack_PickUpItem_C final : public UActionAttackBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ActionAttack_PickUpItem(int32 EntryPoint);
	void BP_OnEndAction(const class FName& nextAction);
	void BP_ActionMain();
	void BP_OnBeginAction(const class FName& prevAction);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionAttack_PickUpItem_C">();
	}
	static class UBP_ActionAttack_PickUpItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionAttack_PickUpItem_C>();
	}
};
static_assert(alignof(UBP_ActionAttack_PickUpItem_C) == 0x000008, "Wrong alignment on UBP_ActionAttack_PickUpItem_C");
static_assert(sizeof(UBP_ActionAttack_PickUpItem_C) == 0x0003D8, "Wrong size on UBP_ActionAttack_PickUpItem_C");
static_assert(offsetof(UBP_ActionAttack_PickUpItem_C, UberGraphFrame) == 0x0003D0, "Member 'UBP_ActionAttack_PickUpItem_C::UberGraphFrame' has a wrong offset!");

}

