#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ch024_Variation0_UniqueSkill

#include "Basic.hpp"

#include "BP_Ch024_Variation0_UniqueSkill_classes.hpp"
#include "BP_Ch024_Variation0_UniqueSkill_parameters.hpp"


namespace SDK
{

// Function BP_Ch024_Variation0_UniqueSkill.BP_Ch024_Variation0_UniqueSkill_C.ExecuteUbergraph_BP_Ch024_Variation0_UniqueSkill
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Ch024_Variation0_UniqueSkill_C::ExecuteUbergraph_BP_Ch024_Variation0_UniqueSkill(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch024_Variation0_UniqueSkill_C", "ExecuteUbergraph_BP_Ch024_Variation0_UniqueSkill");

	Params::BP_Ch024_Variation0_UniqueSkill_C_ExecuteUbergraph_BP_Ch024_Variation0_UniqueSkill Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ch024_Variation0_UniqueSkill.BP_Ch024_Variation0_UniqueSkill_C.BP_OnRegisterEvent
// (Event, Public, BlueprintEvent)

void UBP_Ch024_Variation0_UniqueSkill_C::BP_OnRegisterEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ch024_Variation0_UniqueSkill_C", "BP_OnRegisterEvent");

	UObject::ProcessEvent(Func, nullptr);
}

}

