#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CC_Disp_Health_On_Hit

#include "Basic.hpp"

#include "BP_CC_Disp_Health_On_Hit_classes.hpp"
#include "BP_CC_Disp_Health_On_Hit_parameters.hpp"


namespace SDK
{

// Function BP_CC_Disp_Health_On_Hit.BP_CC_Disp_Health_On_Hit_C.ExecuteUbergraph_BP_CC_Disp_Health_On_Hit
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CC_Disp_Health_On_Hit_C::ExecuteUbergraph_BP_CC_Disp_Health_On_Hit(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CC_Disp_Health_On_Hit_C", "ExecuteUbergraph_BP_CC_Disp_Health_On_Hit");

	Params::BP_CC_Disp_Health_On_Hit_C_ExecuteUbergraph_BP_CC_Disp_Health_On_Hit Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CC_Disp_Health_On_Hit.BP_CC_Disp_Health_On_Hit_C.BP_OnEndCondition
// (Event, Protected, BlueprintEvent)

void UBP_CC_Disp_Health_On_Hit_C::BP_OnEndCondition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CC_Disp_Health_On_Hit_C", "BP_OnEndCondition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CC_Disp_Health_On_Hit.BP_CC_Disp_Health_On_Hit_C.BP_OnBeginCondition
// (Event, Protected, BlueprintEvent)

void UBP_CC_Disp_Health_On_Hit_C::BP_OnBeginCondition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CC_Disp_Health_On_Hit_C", "BP_OnBeginCondition");

	UObject::ProcessEvent(Func, nullptr);
}

}

