#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CC_RollSlot_SPAction_ReloadSpeed_Accel

#include "Basic.hpp"

#include "BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_classes.hpp"
#include "BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_parameters.hpp"


namespace SDK
{

// Function BP_CC_RollSlot_SPAction_ReloadSpeed_Accel.BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C.ExecuteUbergraph_BP_CC_RollSlot_SPAction_ReloadSpeed_Accel
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C::ExecuteUbergraph_BP_CC_RollSlot_SPAction_ReloadSpeed_Accel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C", "ExecuteUbergraph_BP_CC_RollSlot_SPAction_ReloadSpeed_Accel");

	Params::BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C_ExecuteUbergraph_BP_CC_RollSlot_SPAction_ReloadSpeed_Accel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CC_RollSlot_SPAction_ReloadSpeed_Accel.BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C.BP_OnChangeConditionLevel
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   oldLevel                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   newLevel                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C::BP_OnChangeConditionLevel(int32 oldLevel, int32 newLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C", "BP_OnChangeConditionLevel");

	Params::BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C_BP_OnChangeConditionLevel Parms{};

	Parms.oldLevel = oldLevel;
	Parms.newLevel = newLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CC_RollSlot_SPAction_ReloadSpeed_Accel.BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C.BP_OnEndCondition
// (Event, Protected, BlueprintEvent)

void UBP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C::BP_OnEndCondition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C", "BP_OnEndCondition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CC_RollSlot_SPAction_ReloadSpeed_Accel.BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C.BP_OnHiddenCondition
// (Event, Protected, BlueprintEvent)

void UBP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C::BP_OnHiddenCondition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C", "BP_OnHiddenCondition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CC_RollSlot_SPAction_ReloadSpeed_Accel.BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C.BP_OnVisibleCondition
// (Event, Protected, BlueprintEvent)

void UBP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C::BP_OnVisibleCondition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CC_RollSlot_SPAction_ReloadSpeed_Accel_C", "BP_OnVisibleCondition");

	UObject::ProcessEvent(Func, nullptr);
}

}

