#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ReloadPlusUltra_NormalSkill

#include "Basic.hpp"

#include "InGameModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ReloadPlusUltra_NormalSkill.BP_ReloadPlusUltra_NormalSkill_C
// 0x0000 (0x03F0 - 0x03F0)
class UBP_ReloadPlusUltra_NormalSkill_C final : public UReloadPlusUltraRollSlot
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ReloadPlusUltra_NormalSkill_C">();
	}
	static class UBP_ReloadPlusUltra_NormalSkill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ReloadPlusUltra_NormalSkill_C>();
	}
};
static_assert(alignof(UBP_ReloadPlusUltra_NormalSkill_C) == 0x000008, "Wrong alignment on UBP_ReloadPlusUltra_NormalSkill_C");
static_assert(sizeof(UBP_ReloadPlusUltra_NormalSkill_C) == 0x0003F0, "Wrong size on UBP_ReloadPlusUltra_NormalSkill_C");

}

