#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPB_CommonShotNormal

#include "Basic.hpp"

#include "InGameModule_classes.hpp"


namespace SDK
{

// DynamicClass BPB_CommonShotNormal.BPB_CommonShotNormal_C
// 0x0020 (0x1CD0 - 0x1CB0)
class ABPB_CommonShotNormal_C final : public ABullet
{
public:
	class UParticleSystemComponent*               ParticleSystem;                                    // 0x1CA8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCapsuleComponent*                      h1;                                                // 0x1CB0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USphereComponent*                       b1;                                                // 0x1CB8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UProjectileMovementComponent*           ProjectileMovement;                                // 0x1CC0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x1CC8(0x0004)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1CCC[0x4];                                     // 0x1CCC(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ReceiveBeginPlay();
	void ReceiveTick(float bpp__DeltaSeconds__pf);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BPB_CommonShotNormal_C">();
	}
	static class ABPB_CommonShotNormal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPB_CommonShotNormal_C>();
	}
};
static_assert(alignof(ABPB_CommonShotNormal_C) == 0x000010, "Wrong alignment on ABPB_CommonShotNormal_C");
static_assert(sizeof(ABPB_CommonShotNormal_C) == 0x001CD0, "Wrong size on ABPB_CommonShotNormal_C");
static_assert(offsetof(ABPB_CommonShotNormal_C, ParticleSystem) == 0x001CA8, "Member 'ABPB_CommonShotNormal_C::ParticleSystem' has a wrong offset!");
static_assert(offsetof(ABPB_CommonShotNormal_C, h1) == 0x001CB0, "Member 'ABPB_CommonShotNormal_C::h1' has a wrong offset!");
static_assert(offsetof(ABPB_CommonShotNormal_C, b1) == 0x001CB8, "Member 'ABPB_CommonShotNormal_C::b1' has a wrong offset!");
static_assert(offsetof(ABPB_CommonShotNormal_C, ProjectileMovement) == 0x001CC0, "Member 'ABPB_CommonShotNormal_C::ProjectileMovement' has a wrong offset!");
static_assert(offsetof(ABPB_CommonShotNormal_C, K2Node_Event_DeltaSeconds) == 0x001CC8, "Member 'ABPB_CommonShotNormal_C::K2Node_Event_DeltaSeconds' has a wrong offset!");

}

