#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTT_PatrolStart

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTT_PatrolStart.BTT_PatrolStart_C
// 0x0030 (0x00D8 - 0x00A8)
class UBTT_PatrolStart_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FBlackboardKeySelector                 TargetActorKey;                                    // 0x00B0(0x0028)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_BTT_PatrolStart(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTT_PatrolStart_C">();
	}
	static class UBTT_PatrolStart_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTT_PatrolStart_C>();
	}
};
static_assert(alignof(UBTT_PatrolStart_C) == 0x000008, "Wrong alignment on UBTT_PatrolStart_C");
static_assert(sizeof(UBTT_PatrolStart_C) == 0x0000D8, "Wrong size on UBTT_PatrolStart_C");
static_assert(offsetof(UBTT_PatrolStart_C, UberGraphFrame) == 0x0000A8, "Member 'UBTT_PatrolStart_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBTT_PatrolStart_C, TargetActorKey) == 0x0000B0, "Member 'UBTT_PatrolStart_C::TargetActorKey' has a wrong offset!");

}

