#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DebugMenuMasterDataModule

#include "Basic.hpp"

#include "MasterDataModule_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class DebugMenuMasterDataModule.DebugMenuMasterData
// 0x0020 (0x0050 - 0x0030)
class UDebugMenuMasterData final : public ULocalPlayerSubsystem
{
public:
	TMulticastInlineDelegate<void()>              OnCompleteDownload;                                // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TSubclassOf<class UUserWidget>                _debugMenuClass;                                   // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UUserWidget*                            _menuWidget;                                       // 0x0048(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	void Close();
	void CopyMasterData();
	void DeinitializeMasterData();
	void DownloadMasterData();
	class FString GetAllJson(const class FString& TableName);
	class FString GetDatabaseFilePath();
	class FString GetDatabasePassword();
	class FString GetDataFileVersion();
	EMdLocalization GetLanguage();
	class FString GetModuleCodeVersion();
	class FString GetSourceFilePath();
	TArray<class FString> GetTableList();
	void InitializeMasterData();
	bool IsMasterDataInitialized();
	void OnDownloadComplete();
	void Open();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DebugMenuMasterData">();
	}
	static class UDebugMenuMasterData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDebugMenuMasterData>();
	}
};
static_assert(alignof(UDebugMenuMasterData) == 0x000008, "Wrong alignment on UDebugMenuMasterData");
static_assert(sizeof(UDebugMenuMasterData) == 0x000050, "Wrong size on UDebugMenuMasterData");
static_assert(offsetof(UDebugMenuMasterData, OnCompleteDownload) == 0x000030, "Member 'UDebugMenuMasterData::OnCompleteDownload' has a wrong offset!");
static_assert(offsetof(UDebugMenuMasterData, _debugMenuClass) == 0x000040, "Member 'UDebugMenuMasterData::_debugMenuClass' has a wrong offset!");
static_assert(offsetof(UDebugMenuMasterData, _menuWidget) == 0x000048, "Member 'UDebugMenuMasterData::_menuWidget' has a wrong offset!");

}

