#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EQC_FindSupply

#include "Basic.hpp"


namespace SDK::Params
{

// Function EQC_FindSupply.EQC_FindSupply_C.ProvideSingleActor
// 0x0028 (0x0028 - 0x0000)
struct EQC_FindSupply_C_ProvideSingleActor final
{
public:
	class UObject*                                QuerierObject;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 QuerierActor;                                      // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 ResultingActor;                                    // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASupplyActorBase*                       K2Node_DynamicCast_AsSupply_Actor_Base;            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(EQC_FindSupply_C_ProvideSingleActor) == 0x000008, "Wrong alignment on EQC_FindSupply_C_ProvideSingleActor");
static_assert(sizeof(EQC_FindSupply_C_ProvideSingleActor) == 0x000028, "Wrong size on EQC_FindSupply_C_ProvideSingleActor");
static_assert(offsetof(EQC_FindSupply_C_ProvideSingleActor, QuerierObject) == 0x000000, "Member 'EQC_FindSupply_C_ProvideSingleActor::QuerierObject' has a wrong offset!");
static_assert(offsetof(EQC_FindSupply_C_ProvideSingleActor, QuerierActor) == 0x000008, "Member 'EQC_FindSupply_C_ProvideSingleActor::QuerierActor' has a wrong offset!");
static_assert(offsetof(EQC_FindSupply_C_ProvideSingleActor, ResultingActor) == 0x000010, "Member 'EQC_FindSupply_C_ProvideSingleActor::ResultingActor' has a wrong offset!");
static_assert(offsetof(EQC_FindSupply_C_ProvideSingleActor, K2Node_DynamicCast_AsSupply_Actor_Base) == 0x000018, "Member 'EQC_FindSupply_C_ProvideSingleActor::K2Node_DynamicCast_AsSupply_Actor_Base' has a wrong offset!");
static_assert(offsetof(EQC_FindSupply_C_ProvideSingleActor, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'EQC_FindSupply_C_ProvideSingleActor::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

