#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TextChatIconButton

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_TextChatIconButton.WBP_TextChatIconButton_C.SetEnabled
// 0x0001 (0x0001 - 0x0000)
struct WBP_TextChatIconButton_C_SetEnabled final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_TextChatIconButton_C_SetEnabled) == 0x000001, "Wrong alignment on WBP_TextChatIconButton_C_SetEnabled");
static_assert(sizeof(WBP_TextChatIconButton_C_SetEnabled) == 0x000001, "Wrong size on WBP_TextChatIconButton_C_SetEnabled");
static_assert(offsetof(WBP_TextChatIconButton_C_SetEnabled, Enabled) == 0x000000, "Member 'WBP_TextChatIconButton_C_SetEnabled::Enabled' has a wrong offset!");

}

