#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FocusAnimationListItem

#include "Basic.hpp"

#include "UIFramework_structs.hpp"
#include "Engine_structs.hpp"
#include "GameModule_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_FocusAnimationListItem.WBP_FocusAnimationListItem_C
// 0x0068 (0x04E8 - 0x0480)
class UWBP_FocusAnimationListItem_C final : public UFocusAnimationWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0480(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Ani_LongPress;                                     // 0x0488(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ani_ReleaseShortcut;                               // 0x0490(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ani_PressShortcut;                                 // 0x0498(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ani_Negative;                                      // 0x04A0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ani_FocusLoop;                                     // 0x04A8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ani_FocusEnd;                                      // 0x04B0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ani_FocusBegin;                                    // 0x04B8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ani_Default;                                       // 0x04C0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ani_Release;                                       // 0x04C8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ani_Press;                                         // 0x04D0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UNamedSlot*                             ButtonBody;                                        // 0x04D8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             TopLayer;                                          // 0x04E0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_FocusAnimationListItem(int32 EntryPoint);
	void OnRemovedFromFocusDelegate(class UAppWidget* Widget, EWidgetInputType inputType);
	void Construct();
	void UpdateFocusWhite(class UImage* _focusWhite_0, ESlateVisibility Visibility_0);
	void UpdateFocusTop(class UImage* _focusTop_0);
	void SequenceEvent__ENTRYPOINTWBP_FocusAnimationListItem_0(class UImage* _focusTop_0);
	void SequenceEvent__ENTRYPOINTWBP_FocusAnimationListItem_1(class UImage* _focusTop_0);
	void SequenceEvent__ENTRYPOINTWBP_FocusAnimationListItem_2(class UImage* _focusTop_0);
	void SequenceEvent__ENTRYPOINTWBP_FocusAnimationListItem_3(class UImage* _focusWhite_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_FocusAnimationListItem_C">();
	}
	static class UWBP_FocusAnimationListItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FocusAnimationListItem_C>();
	}
};
static_assert(alignof(UWBP_FocusAnimationListItem_C) == 0x000008, "Wrong alignment on UWBP_FocusAnimationListItem_C");
static_assert(sizeof(UWBP_FocusAnimationListItem_C) == 0x0004E8, "Wrong size on UWBP_FocusAnimationListItem_C");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, UberGraphFrame) == 0x000480, "Member 'UWBP_FocusAnimationListItem_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, Ani_LongPress) == 0x000488, "Member 'UWBP_FocusAnimationListItem_C::Ani_LongPress' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, Ani_ReleaseShortcut) == 0x000490, "Member 'UWBP_FocusAnimationListItem_C::Ani_ReleaseShortcut' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, Ani_PressShortcut) == 0x000498, "Member 'UWBP_FocusAnimationListItem_C::Ani_PressShortcut' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, Ani_Negative) == 0x0004A0, "Member 'UWBP_FocusAnimationListItem_C::Ani_Negative' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, Ani_FocusLoop) == 0x0004A8, "Member 'UWBP_FocusAnimationListItem_C::Ani_FocusLoop' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, Ani_FocusEnd) == 0x0004B0, "Member 'UWBP_FocusAnimationListItem_C::Ani_FocusEnd' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, Ani_FocusBegin) == 0x0004B8, "Member 'UWBP_FocusAnimationListItem_C::Ani_FocusBegin' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, Ani_Default) == 0x0004C0, "Member 'UWBP_FocusAnimationListItem_C::Ani_Default' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, Ani_Release) == 0x0004C8, "Member 'UWBP_FocusAnimationListItem_C::Ani_Release' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, Ani_Press) == 0x0004D0, "Member 'UWBP_FocusAnimationListItem_C::Ani_Press' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, ButtonBody) == 0x0004D8, "Member 'UWBP_FocusAnimationListItem_C::ButtonBody' has a wrong offset!");
static_assert(offsetof(UWBP_FocusAnimationListItem_C, TopLayer) == 0x0004E0, "Member 'UWBP_FocusAnimationListItem_C::TopLayer' has a wrong offset!");

}

