#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GeneralWindowFrame

#include "Basic.hpp"

#include "UIFramework_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_GeneralWindowFrame.WBP_GeneralWindowFrame_C
// 0x00A0 (0x0680 - 0x05E0)
class UWBP_GeneralWindowFrame_C final : public UWidgetGeneralWindowFrame
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       ani_out;                                           // 0x05E8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Ani_Idle;                                          // 0x05F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ani_in;                                            // 0x05F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 BlockBG;                                           // 0x0600(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Black;                                       // 0x0608(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_155;                                   // 0x0610(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USoundAtomCue*                          oneButtonPressOverride;                            // 0x0618(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundAtomCue*                          leftButtonPressOverride;                           // 0x0620(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundAtomCue*                          rightButtonPressOverride;                          // 0x0628(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundAtomCue*                          rightButtonFocusOverride;                          // 0x0630(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundAtomCue*                          rightButtonShortcutOverride;                       // 0x0638(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundAtomCue*                          rightButtonNegativeOverride;                       // 0x0640(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundAtomCue*                          leftButtonFocusOverride;                           // 0x0648(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundAtomCue*                          leftButtonShortcutOverride;                        // 0x0650(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundAtomCue*                          leftButtonNegativeOverride;                        // 0x0658(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundAtomCue*                          oneButtonFocusOverride;                            // 0x0660(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundAtomCue*                          oneButtonShortcutOverride;                         // 0x0668(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundAtomCue*                          oneButtonNegativeOverride;                         // 0x0670(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ButtonSize;                                        // 0x0678(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ButtonSpaceSize;                                   // 0x067C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_GeneralWindowFrame(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void OnClose();
	void OnOpen();
	struct FEventReply On_BlockBG_MouseButtonDown_0(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void PreConstructSE();
	void SetOverridePressAtomCue(class USoundAtomCue* overrideAtomCue, class UWidgetButton* Button);
	void SetOverrideFocusAtomCue(class USoundAtomCue* overrideAtomCue, class UWidgetButton* Button);
	void SetOverrideShortcutAtomCue(class USoundAtomCue* overrideAtomCue, class UWidgetButton* Button);
	void SetOverrideNegativeAtomCue(class USoundAtomCue* overrideAtomCue, class UWidgetButton* Button);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_GeneralWindowFrame_C">();
	}
	static class UWBP_GeneralWindowFrame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_GeneralWindowFrame_C>();
	}
};
static_assert(alignof(UWBP_GeneralWindowFrame_C) == 0x000008, "Wrong alignment on UWBP_GeneralWindowFrame_C");
static_assert(sizeof(UWBP_GeneralWindowFrame_C) == 0x000680, "Wrong size on UWBP_GeneralWindowFrame_C");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, UberGraphFrame) == 0x0005E0, "Member 'UWBP_GeneralWindowFrame_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, ani_out) == 0x0005E8, "Member 'UWBP_GeneralWindowFrame_C::ani_out' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, Ani_Idle) == 0x0005F0, "Member 'UWBP_GeneralWindowFrame_C::Ani_Idle' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, ani_in) == 0x0005F8, "Member 'UWBP_GeneralWindowFrame_C::ani_in' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, BlockBG) == 0x000600, "Member 'UWBP_GeneralWindowFrame_C::BlockBG' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, Image_Black) == 0x000608, "Member 'UWBP_GeneralWindowFrame_C::Image_Black' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, VerticalBox_155) == 0x000610, "Member 'UWBP_GeneralWindowFrame_C::VerticalBox_155' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, oneButtonPressOverride) == 0x000618, "Member 'UWBP_GeneralWindowFrame_C::oneButtonPressOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, leftButtonPressOverride) == 0x000620, "Member 'UWBP_GeneralWindowFrame_C::leftButtonPressOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, rightButtonPressOverride) == 0x000628, "Member 'UWBP_GeneralWindowFrame_C::rightButtonPressOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, rightButtonFocusOverride) == 0x000630, "Member 'UWBP_GeneralWindowFrame_C::rightButtonFocusOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, rightButtonShortcutOverride) == 0x000638, "Member 'UWBP_GeneralWindowFrame_C::rightButtonShortcutOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, rightButtonNegativeOverride) == 0x000640, "Member 'UWBP_GeneralWindowFrame_C::rightButtonNegativeOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, leftButtonFocusOverride) == 0x000648, "Member 'UWBP_GeneralWindowFrame_C::leftButtonFocusOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, leftButtonShortcutOverride) == 0x000650, "Member 'UWBP_GeneralWindowFrame_C::leftButtonShortcutOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, leftButtonNegativeOverride) == 0x000658, "Member 'UWBP_GeneralWindowFrame_C::leftButtonNegativeOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, oneButtonFocusOverride) == 0x000660, "Member 'UWBP_GeneralWindowFrame_C::oneButtonFocusOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, oneButtonShortcutOverride) == 0x000668, "Member 'UWBP_GeneralWindowFrame_C::oneButtonShortcutOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, oneButtonNegativeOverride) == 0x000670, "Member 'UWBP_GeneralWindowFrame_C::oneButtonNegativeOverride' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, ButtonSize) == 0x000678, "Member 'UWBP_GeneralWindowFrame_C::ButtonSize' has a wrong offset!");
static_assert(offsetof(UWBP_GeneralWindowFrame_C, ButtonSpaceSize) == 0x00067C, "Member 'UWBP_GeneralWindowFrame_C::ButtonSpaceSize' has a wrong offset!");

}

