#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VoiceChatMenu

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "VoiceChatModule_structs.hpp"


namespace SDK::Params
{

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.ExecuteUbergraph_WBP_VoiceChatMenu
// 0x0308 (0x0308 - 0x0000)
struct WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UDebugMenuVoiceChat*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsChecked_1;           // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_ComponentBoundEvent_SelectedItem_2;         // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   K2Node_ComponentBoundEvent_SelectionType_2;        // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_ComponentBoundEvent_SelectedItem_1;         // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   K2Node_ComponentBoundEvent_SelectionType_1;        // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDebugMenuVoiceChat*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue_1;    // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_ComponentBoundEvent_SelectedItem;           // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   K2Node_ComponentBoundEvent_SelectionType;          // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         CallFunc_GetInputDeviceNames_ReturnValue;          // 0x0068(0x0010)(ReferenceParm)
	TArray<class FString>                         CallFunc_GetOutputDeviceNames_ReturnValue;         // 0x0078(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue;                  // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Initialize_ReturnValue;                   // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_1;                // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_2;                // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_3;                // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAudioOutputMuted_ReturnValue;           // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsAudioInputMuted_ReturnValue;            // 0x00B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BA[0x2];                                       // 0x00BA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_4;                // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Array_Get_Item;                           // 0x00C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x00D8(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetSelectedIndex_ReturnValue;             // 0x0114(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetOutputDeviceIdByIndex_ReturnValue;     // 0x0118(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_5;                // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetSelectedIndex_ReturnValue_1;           // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsChecked;             // 0x0134(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_135[0x3];                                      // 0x0135(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_6;                // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_7;                // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_ComponentBoundEvent_Text;                   // 0x0148(0x0018)(ConstParm)
	float                                         K2Node_ComponentBoundEvent_InValue_2;              // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_164[0x4];                                      // 0x0164(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0168(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	float                                         K2Node_ComponentBoundEvent_InValue_1;              // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17C[0x4];                                      // 0x017C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_8;                // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_9;                // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0194(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_195[0x3];                                      // 0x0195(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19C[0x4];                                      // 0x019C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_10;               // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1AC[0x4];                                      // 0x01AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Array_Get_Item_1;                         // 0x01B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_11;               // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_playerName;                     // 0x01C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	EVoiceChatPlayerStatus                        K2Node_CustomEvent_status;                         // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D9[0x3];                                      // 0x01D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_CustomEvent_value;                          // 0x01DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E1[0x7];                                      // 0x01E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Get_Selected_Member_MemberName;           // 0x01E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_12;               // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Get_Selected_Member_MemberName_1;         // 0x0200(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_13;               // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Get_Selected_Member_MemberName_2;         // 0x0218(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_14;               // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                K2Node_ComponentBoundEvent_Item;                   // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsSelected;            // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_239[0x7];                                      // 0x0239(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Get_Selected_Member_MemberName_3;         // 0x0240(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_15;               // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayerMuted_ReturnValue;                // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_259[0x3];                                      // 0x0259(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& PlayerName, EVoiceChatPlayerStatus Status, float value)> K2Node_CreateDelegate_OutputDelegate; // 0x025C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_26C[0x4];                                      // 0x026C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Get_Selected_Member_MemberName_4;         // 0x0270(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_16;               // 0x0280(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDebugMenuVoiceChat*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue_2;    // 0x0288(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_ComponentBoundEvent_InValue;                // 0x0290(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_294[0x4];                                      // 0x0294(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Get_Selected_Member_MemberName_5;         // 0x0298(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_17;               // 0x02A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDebugMenuVoiceChat*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue_3;    // 0x02B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetStatusText_ReturnValue;                // 0x02B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x02C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x02CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2CD[0x3];                                      // 0x02CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x02D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D4[0x4];                                      // 0x02D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UDebugMenuVoiceChat*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue_4;    // 0x02D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDebugMenuVoiceChat*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue_5;    // 0x02E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetPlayerName_ReturnValue;                // 0x02E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetInputDeviceIdByIndex_ReturnValue;      // 0x02F8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu");
static_assert(sizeof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu) == 0x000308, "Wrong size on WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, EntryPoint) == 0x000000, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000008, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_bIsChecked_1) == 0x000010, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_bIsChecked_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_SelectedItem_2) == 0x000018, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_SelectedItem_2' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_SelectionType_2) == 0x000028, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_SelectionType_2' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_SelectedItem_1) == 0x000030, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_SelectedItem_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_SelectionType_1) == 0x000040, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_SelectionType_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetLocalPlayerSubsystem_ReturnValue_1) == 0x000048, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetLocalPlayerSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_SelectedItem) == 0x000050, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_SelectedItem' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_SelectionType) == 0x000060, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_SelectionType' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInputDeviceNames_ReturnValue) == 0x000068, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInputDeviceNames_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetOutputDeviceNames_ReturnValue) == 0x000078, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetOutputDeviceNames_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Array_Length_ReturnValue) == 0x000088, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Array_Length_ReturnValue_1) == 0x00008C, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue) == 0x000090, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Initialize_ReturnValue) == 0x000098, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Initialize_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_1) == 0x0000A0, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_2) == 0x0000A8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_3) == 0x0000B0, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_IsAudioOutputMuted_ReturnValue) == 0x0000B8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_IsAudioOutputMuted_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_IsAudioInputMuted_ReturnValue) == 0x0000B9, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_IsAudioInputMuted_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, Temp_int_Array_Index_Variable) == 0x0000BC, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_4) == 0x0000C0, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Array_Get_Item) == 0x0000C8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_Event_MyGeometry) == 0x0000D8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_Event_InDeltaTime) == 0x000110, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetSelectedIndex_ReturnValue) == 0x000114, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetSelectedIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetOutputDeviceIdByIndex_ReturnValue) == 0x000118, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetOutputDeviceIdByIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_5) == 0x000128, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetSelectedIndex_ReturnValue_1) == 0x000130, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetSelectedIndex_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_bIsChecked) == 0x000134, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_bIsChecked' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_6) == 0x000138, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_7) == 0x000140, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_Text) == 0x000148, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_Text' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_InValue_2) == 0x000160, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_InValue_2' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Conv_TextToString_ReturnValue) == 0x000168, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_InValue_1) == 0x000178, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_InValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_8) == 0x000180, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_9) == 0x000188, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, Temp_int_Loop_Counter_Variable) == 0x000190, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Less_IntInt_ReturnValue) == 0x000194, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Add_IntInt_ReturnValue) == 0x000198, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_10) == 0x0001A0, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, Temp_int_Array_Index_Variable_1) == 0x0001A8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Array_Get_Item_1) == 0x0001B0, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_11) == 0x0001C0, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_CustomEvent_playerName) == 0x0001C8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_CustomEvent_playerName' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_CustomEvent_status) == 0x0001D8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_CustomEvent_status' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_CustomEvent_value) == 0x0001DC, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_CustomEvent_value' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_SwitchEnum_CmpSuccess) == 0x0001E0, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Get_Selected_Member_MemberName) == 0x0001E8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Get_Selected_Member_MemberName' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_12) == 0x0001F8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Get_Selected_Member_MemberName_1) == 0x000200, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Get_Selected_Member_MemberName_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_13) == 0x000210, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Get_Selected_Member_MemberName_2) == 0x000218, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Get_Selected_Member_MemberName_2' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_14) == 0x000228, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_Item) == 0x000230, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_Item' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_bIsSelected) == 0x000238, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_bIsSelected' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Get_Selected_Member_MemberName_3) == 0x000240, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Get_Selected_Member_MemberName_3' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_15) == 0x000250, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_15' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_IsPlayerMuted_ReturnValue) == 0x000258, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_IsPlayerMuted_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_CreateDelegate_OutputDelegate) == 0x00025C, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Get_Selected_Member_MemberName_4) == 0x000270, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Get_Selected_Member_MemberName_4' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_16) == 0x000280, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_16' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetLocalPlayerSubsystem_ReturnValue_2) == 0x000288, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetLocalPlayerSubsystem_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, K2Node_ComponentBoundEvent_InValue) == 0x000290, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::K2Node_ComponentBoundEvent_InValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Get_Selected_Member_MemberName_5) == 0x000298, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Get_Selected_Member_MemberName_5' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInstance_ReturnValue_17) == 0x0002A8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInstance_ReturnValue_17' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetLocalPlayerSubsystem_ReturnValue_3) == 0x0002B0, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetLocalPlayerSubsystem_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetStatusText_ReturnValue) == 0x0002B8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetStatusText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, Temp_int_Loop_Counter_Variable_1) == 0x0002C8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Less_IntInt_ReturnValue_1) == 0x0002CC, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_Add_IntInt_ReturnValue_1) == 0x0002D0, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetLocalPlayerSubsystem_ReturnValue_4) == 0x0002D8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetLocalPlayerSubsystem_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetLocalPlayerSubsystem_ReturnValue_5) == 0x0002E0, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetLocalPlayerSubsystem_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetPlayerName_ReturnValue) == 0x0002E8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetPlayerName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu, CallFunc_GetInputDeviceIdByIndex_ReturnValue) == 0x0002F8, "Member 'WBP_VoiceChatMenu_C_ExecuteUbergraph_WBP_VoiceChatMenu::CallFunc_GetInputDeviceIdByIndex_ReturnValue' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.BndEvt__WBP_VoiceChatMenu_SpinBoxPlayerVolume_K2Node_ComponentBoundEvent_14_OnSpinBoxValueChangedEvent__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxPlayerVolume_K2Node_ComponentBoundEvent_14_OnSpinBoxValueChangedEvent__DelegateSignature final
{
public:
	float                                         InValue;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxPlayerVolume_K2Node_ComponentBoundEvent_14_OnSpinBoxValueChangedEvent__DelegateSignature) == 0x000004, "Wrong alignment on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxPlayerVolume_K2Node_ComponentBoundEvent_14_OnSpinBoxValueChangedEvent__DelegateSignature");
static_assert(sizeof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxPlayerVolume_K2Node_ComponentBoundEvent_14_OnSpinBoxValueChangedEvent__DelegateSignature) == 0x000004, "Wrong size on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxPlayerVolume_K2Node_ComponentBoundEvent_14_OnSpinBoxValueChangedEvent__DelegateSignature");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxPlayerVolume_K2Node_ComponentBoundEvent_14_OnSpinBoxValueChangedEvent__DelegateSignature, InValue) == 0x000000, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxPlayerVolume_K2Node_ComponentBoundEvent_14_OnSpinBoxValueChangedEvent__DelegateSignature::InValue' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.BndEvt__WBP_VoiceChatMenu_ListChatMembers_K2Node_ComponentBoundEvent_12_OnListItemSelectionChangedDynamic__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ListChatMembers_K2Node_ComponentBoundEvent_12_OnListItemSelectionChangedDynamic__DelegateSignature final
{
public:
	class UObject*                                Item;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsSelected;                                       // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ListChatMembers_K2Node_ComponentBoundEvent_12_OnListItemSelectionChangedDynamic__DelegateSignature) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ListChatMembers_K2Node_ComponentBoundEvent_12_OnListItemSelectionChangedDynamic__DelegateSignature");
static_assert(sizeof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ListChatMembers_K2Node_ComponentBoundEvent_12_OnListItemSelectionChangedDynamic__DelegateSignature) == 0x000010, "Wrong size on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ListChatMembers_K2Node_ComponentBoundEvent_12_OnListItemSelectionChangedDynamic__DelegateSignature");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ListChatMembers_K2Node_ComponentBoundEvent_12_OnListItemSelectionChangedDynamic__DelegateSignature, Item) == 0x000000, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ListChatMembers_K2Node_ComponentBoundEvent_12_OnListItemSelectionChangedDynamic__DelegateSignature::Item' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ListChatMembers_K2Node_ComponentBoundEvent_12_OnListItemSelectionChangedDynamic__DelegateSignature, bIsSelected) == 0x000008, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ListChatMembers_K2Node_ComponentBoundEvent_12_OnListItemSelectionChangedDynamic__DelegateSignature::bIsSelected' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.プレイヤーの状態変化
// 0x0018 (0x0018 - 0x0000)
struct WBP_VoiceChatMenu_C_プレイヤーの状態変化 final
{
public:
	class FString                                 PlayerName_0;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	EVoiceChatPlayerStatus                        Status;                                            // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         value;                                             // 0x0014(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_プレイヤーの状態変化) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_プレイヤーの状態変化");
static_assert(sizeof(WBP_VoiceChatMenu_C_プレイヤーの状態変化) == 0x000018, "Wrong size on WBP_VoiceChatMenu_C_プレイヤーの状態変化");
static_assert(offsetof(WBP_VoiceChatMenu_C_プレイヤーの状態変化, PlayerName_0) == 0x000000, "Member 'WBP_VoiceChatMenu_C_プレイヤーの状態変化::PlayerName_0' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_プレイヤーの状態変化, Status) == 0x000010, "Member 'WBP_VoiceChatMenu_C_プレイヤーの状態変化::Status' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_プレイヤーの状態変化, value) == 0x000014, "Member 'WBP_VoiceChatMenu_C_プレイヤーの状態変化::value' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.BndEvt__WBP_VoiceChatMenu_SpinBoxSpeakerVolume_K2Node_ComponentBoundEvent_6_OnSpinBoxValueChangedEvent__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxSpeakerVolume_K2Node_ComponentBoundEvent_6_OnSpinBoxValueChangedEvent__DelegateSignature final
{
public:
	float                                         InValue;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxSpeakerVolume_K2Node_ComponentBoundEvent_6_OnSpinBoxValueChangedEvent__DelegateSignature) == 0x000004, "Wrong alignment on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxSpeakerVolume_K2Node_ComponentBoundEvent_6_OnSpinBoxValueChangedEvent__DelegateSignature");
static_assert(sizeof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxSpeakerVolume_K2Node_ComponentBoundEvent_6_OnSpinBoxValueChangedEvent__DelegateSignature) == 0x000004, "Wrong size on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxSpeakerVolume_K2Node_ComponentBoundEvent_6_OnSpinBoxValueChangedEvent__DelegateSignature");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxSpeakerVolume_K2Node_ComponentBoundEvent_6_OnSpinBoxValueChangedEvent__DelegateSignature, InValue) == 0x000000, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxSpeakerVolume_K2Node_ComponentBoundEvent_6_OnSpinBoxValueChangedEvent__DelegateSignature::InValue' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.BndEvt__WBP_VoiceChatMenu_SpinBoxMicVolume_K2Node_ComponentBoundEvent_5_OnSpinBoxValueChangedEvent__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxMicVolume_K2Node_ComponentBoundEvent_5_OnSpinBoxValueChangedEvent__DelegateSignature final
{
public:
	float                                         InValue;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxMicVolume_K2Node_ComponentBoundEvent_5_OnSpinBoxValueChangedEvent__DelegateSignature) == 0x000004, "Wrong alignment on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxMicVolume_K2Node_ComponentBoundEvent_5_OnSpinBoxValueChangedEvent__DelegateSignature");
static_assert(sizeof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxMicVolume_K2Node_ComponentBoundEvent_5_OnSpinBoxValueChangedEvent__DelegateSignature) == 0x000004, "Wrong size on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxMicVolume_K2Node_ComponentBoundEvent_5_OnSpinBoxValueChangedEvent__DelegateSignature");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxMicVolume_K2Node_ComponentBoundEvent_5_OnSpinBoxValueChangedEvent__DelegateSignature, InValue) == 0x000000, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_SpinBoxMicVolume_K2Node_ComponentBoundEvent_5_OnSpinBoxValueChangedEvent__DelegateSignature::InValue' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.BndEvt__WBP_VoiceChatMenu_EditableTextChanelName_K2Node_ComponentBoundEvent_4_OnEditableTextBoxChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_EditableTextChanelName_K2Node_ComponentBoundEvent_4_OnEditableTextBoxChangedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_EditableTextChanelName_K2Node_ComponentBoundEvent_4_OnEditableTextBoxChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_EditableTextChanelName_K2Node_ComponentBoundEvent_4_OnEditableTextBoxChangedEvent__DelegateSignature");
static_assert(sizeof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_EditableTextChanelName_K2Node_ComponentBoundEvent_4_OnEditableTextBoxChangedEvent__DelegateSignature) == 0x000018, "Wrong size on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_EditableTextChanelName_K2Node_ComponentBoundEvent_4_OnEditableTextBoxChangedEvent__DelegateSignature");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_EditableTextChanelName_K2Node_ComponentBoundEvent_4_OnEditableTextBoxChangedEvent__DelegateSignature, Text) == 0x000000, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_EditableTextChanelName_K2Node_ComponentBoundEvent_4_OnEditableTextBoxChangedEvent__DelegateSignature::Text' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.BndEvt__WBP_VoiceChatMenu_CheckBoxMicMute_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMicMute_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature final
{
public:
	bool                                          bIsChecked;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMicMute_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMicMute_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(sizeof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMicMute_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong size on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMicMute_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMicMute_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature, bIsChecked) == 0x000000, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMicMute_K2Node_ComponentBoundEvent_2_OnCheckBoxComponentStateChanged__DelegateSignature::bIsChecked' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.BndEvt__WBP_VoiceChatMenu_ComboBoxMode_K2Node_ComponentBoundEvent_3_OnSelectionChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMode_K2Node_ComponentBoundEvent_3_OnSelectionChangedEvent__DelegateSignature final
{
public:
	class FString                                 SelectedItem;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   SelectionType;                                     // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMode_K2Node_ComponentBoundEvent_3_OnSelectionChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMode_K2Node_ComponentBoundEvent_3_OnSelectionChangedEvent__DelegateSignature");
static_assert(sizeof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMode_K2Node_ComponentBoundEvent_3_OnSelectionChangedEvent__DelegateSignature) == 0x000018, "Wrong size on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMode_K2Node_ComponentBoundEvent_3_OnSelectionChangedEvent__DelegateSignature");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMode_K2Node_ComponentBoundEvent_3_OnSelectionChangedEvent__DelegateSignature, SelectedItem) == 0x000000, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMode_K2Node_ComponentBoundEvent_3_OnSelectionChangedEvent__DelegateSignature::SelectedItem' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMode_K2Node_ComponentBoundEvent_3_OnSelectionChangedEvent__DelegateSignature, SelectionType) == 0x000010, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMode_K2Node_ComponentBoundEvent_3_OnSelectionChangedEvent__DelegateSignature::SelectionType' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.BndEvt__WBP_VoiceChatMenu_ComboBoxMicDevice_K2Node_ComponentBoundEvent_48_OnSelectionChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMicDevice_K2Node_ComponentBoundEvent_48_OnSelectionChangedEvent__DelegateSignature final
{
public:
	class FString                                 SelectedItem;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   SelectionType;                                     // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMicDevice_K2Node_ComponentBoundEvent_48_OnSelectionChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMicDevice_K2Node_ComponentBoundEvent_48_OnSelectionChangedEvent__DelegateSignature");
static_assert(sizeof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMicDevice_K2Node_ComponentBoundEvent_48_OnSelectionChangedEvent__DelegateSignature) == 0x000018, "Wrong size on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMicDevice_K2Node_ComponentBoundEvent_48_OnSelectionChangedEvent__DelegateSignature");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMicDevice_K2Node_ComponentBoundEvent_48_OnSelectionChangedEvent__DelegateSignature, SelectedItem) == 0x000000, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMicDevice_K2Node_ComponentBoundEvent_48_OnSelectionChangedEvent__DelegateSignature::SelectedItem' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMicDevice_K2Node_ComponentBoundEvent_48_OnSelectionChangedEvent__DelegateSignature, SelectionType) == 0x000010, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxMicDevice_K2Node_ComponentBoundEvent_48_OnSelectionChangedEvent__DelegateSignature::SelectionType' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.BndEvt__WBP_VoiceChatMenu_ComboBoxSpeakerDevice_K2Node_ComponentBoundEvent_47_OnSelectionChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxSpeakerDevice_K2Node_ComponentBoundEvent_47_OnSelectionChangedEvent__DelegateSignature final
{
public:
	class FString                                 SelectedItem;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   SelectionType;                                     // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxSpeakerDevice_K2Node_ComponentBoundEvent_47_OnSelectionChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxSpeakerDevice_K2Node_ComponentBoundEvent_47_OnSelectionChangedEvent__DelegateSignature");
static_assert(sizeof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxSpeakerDevice_K2Node_ComponentBoundEvent_47_OnSelectionChangedEvent__DelegateSignature) == 0x000018, "Wrong size on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxSpeakerDevice_K2Node_ComponentBoundEvent_47_OnSelectionChangedEvent__DelegateSignature");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxSpeakerDevice_K2Node_ComponentBoundEvent_47_OnSelectionChangedEvent__DelegateSignature, SelectedItem) == 0x000000, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxSpeakerDevice_K2Node_ComponentBoundEvent_47_OnSelectionChangedEvent__DelegateSignature::SelectedItem' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxSpeakerDevice_K2Node_ComponentBoundEvent_47_OnSelectionChangedEvent__DelegateSignature, SelectionType) == 0x000010, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_ComboBoxSpeakerDevice_K2Node_ComponentBoundEvent_47_OnSelectionChangedEvent__DelegateSignature::SelectionType' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.BndEvt__WBP_VoiceChatMenu_CheckBoxMute_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMute_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature final
{
public:
	bool                                          bIsChecked;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMute_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMute_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(sizeof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMute_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong size on WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMute_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(offsetof(WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMute_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature, bIsChecked) == 0x000000, "Member 'WBP_VoiceChatMenu_C_BndEvt__WBP_VoiceChatMenu_CheckBoxMute_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature::bIsChecked' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.Tick
// 0x003C (0x003C - 0x0000)
struct WBP_VoiceChatMenu_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_Tick) == 0x000004, "Wrong alignment on WBP_VoiceChatMenu_C_Tick");
static_assert(sizeof(WBP_VoiceChatMenu_C_Tick) == 0x00003C, "Wrong size on WBP_VoiceChatMenu_C_Tick");
static_assert(offsetof(WBP_VoiceChatMenu_C_Tick, MyGeometry) == 0x000000, "Member 'WBP_VoiceChatMenu_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Tick, InDeltaTime) == 0x000038, "Member 'WBP_VoiceChatMenu_C_Tick::InDeltaTime' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.SetSelectedMode
// 0x0020 (0x0020 - 0x0000)
struct WBP_VoiceChatMenu_C_SetSelectedMode final
{
public:
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue;                  // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_1;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVoiceChatObject*                       CallFunc_GetInstance_ReturnValue_2;                // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetSelectedIndex_ReturnValue;             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoiceChatMenu_C_SetSelectedMode) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_SetSelectedMode");
static_assert(sizeof(WBP_VoiceChatMenu_C_SetSelectedMode) == 0x000020, "Wrong size on WBP_VoiceChatMenu_C_SetSelectedMode");
static_assert(offsetof(WBP_VoiceChatMenu_C_SetSelectedMode, CallFunc_GetInstance_ReturnValue) == 0x000000, "Member 'WBP_VoiceChatMenu_C_SetSelectedMode::CallFunc_GetInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_SetSelectedMode, CallFunc_GetInstance_ReturnValue_1) == 0x000008, "Member 'WBP_VoiceChatMenu_C_SetSelectedMode::CallFunc_GetInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_SetSelectedMode, CallFunc_GetInstance_ReturnValue_2) == 0x000010, "Member 'WBP_VoiceChatMenu_C_SetSelectedMode::CallFunc_GetInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_SetSelectedMode, CallFunc_GetSelectedIndex_ReturnValue) == 0x000018, "Member 'WBP_VoiceChatMenu_C_SetSelectedMode::CallFunc_GetSelectedIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_SetSelectedMode, K2Node_SwitchInteger_CmpSuccess) == 0x00001C, "Member 'WBP_VoiceChatMenu_C_SetSelectedMode::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.UpdateMemberList
// 0x0060 (0x0060 - 0x0000)
struct WBP_VoiceChatMenu_C_UpdateMemberList final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UDebugMenuVoiceChat*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         CallFunc_GetChannelMemberNames_ReturnValue;        // 0x0018(0x0010)(ReferenceParm)
	class FString                                 CallFunc_Array_Get_Item;                           // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UWBP_EntryItemMemberName_C*             CallFunc_SpawnObject_ReturnValue;                  // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0040(0x0018)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoiceChatMenu_C_UpdateMemberList) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_UpdateMemberList");
static_assert(sizeof(WBP_VoiceChatMenu_C_UpdateMemberList) == 0x000060, "Wrong size on WBP_VoiceChatMenu_C_UpdateMemberList");
static_assert(offsetof(WBP_VoiceChatMenu_C_UpdateMemberList, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_VoiceChatMenu_C_UpdateMemberList::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_UpdateMemberList, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_VoiceChatMenu_C_UpdateMemberList::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_UpdateMemberList, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'WBP_VoiceChatMenu_C_UpdateMemberList::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_UpdateMemberList, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000010, "Member 'WBP_VoiceChatMenu_C_UpdateMemberList::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_UpdateMemberList, CallFunc_GetChannelMemberNames_ReturnValue) == 0x000018, "Member 'WBP_VoiceChatMenu_C_UpdateMemberList::CallFunc_GetChannelMemberNames_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_UpdateMemberList, CallFunc_Array_Get_Item) == 0x000028, "Member 'WBP_VoiceChatMenu_C_UpdateMemberList::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_UpdateMemberList, CallFunc_SpawnObject_ReturnValue) == 0x000038, "Member 'WBP_VoiceChatMenu_C_UpdateMemberList::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_UpdateMemberList, CallFunc_Conv_StringToText_ReturnValue) == 0x000040, "Member 'WBP_VoiceChatMenu_C_UpdateMemberList::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_UpdateMemberList, CallFunc_Array_Length_ReturnValue) == 0x000058, "Member 'WBP_VoiceChatMenu_C_UpdateMemberList::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_UpdateMemberList, CallFunc_Less_IntInt_ReturnValue) == 0x00005C, "Member 'WBP_VoiceChatMenu_C_UpdateMemberList::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.Get Selected Member
// 0x0038 (0x0038 - 0x0000)
struct WBP_VoiceChatMenu_C_Get_Selected_Member final
{
public:
	class FString                                 MemberName;                                        // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_BP_GetSelectedItem_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_EntryItemMemberName_C*             K2Node_DynamicCast_AsWBP_Entry_Item_Member_Name;   // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_Get_Selected_Member) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_Get_Selected_Member");
static_assert(sizeof(WBP_VoiceChatMenu_C_Get_Selected_Member) == 0x000038, "Wrong size on WBP_VoiceChatMenu_C_Get_Selected_Member");
static_assert(offsetof(WBP_VoiceChatMenu_C_Get_Selected_Member, MemberName) == 0x000000, "Member 'WBP_VoiceChatMenu_C_Get_Selected_Member::MemberName' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Get_Selected_Member, CallFunc_BP_GetSelectedItem_ReturnValue) == 0x000010, "Member 'WBP_VoiceChatMenu_C_Get_Selected_Member::CallFunc_BP_GetSelectedItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Get_Selected_Member, K2Node_DynamicCast_AsWBP_Entry_Item_Member_Name) == 0x000018, "Member 'WBP_VoiceChatMenu_C_Get_Selected_Member::K2Node_DynamicCast_AsWBP_Entry_Item_Member_Name' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Get_Selected_Member, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'WBP_VoiceChatMenu_C_Get_Selected_Member::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Get_Selected_Member, CallFunc_Conv_TextToString_ReturnValue) == 0x000028, "Member 'WBP_VoiceChatMenu_C_Get_Selected_Member::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.Update Talking Member List
// 0x0060 (0x0060 - 0x0000)
struct WBP_VoiceChatMenu_C_Update_Talking_Member_List final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDebugMenuVoiceChat*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         CallFunc_GetTalkingMemberNames_ReturnValue;        // 0x0010(0x0010)(ReferenceParm)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Array_Get_Item;                           // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0038(0x0018)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_EntryItemMemberName_C*             CallFunc_SpawnObject_ReturnValue;                  // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_Update_Talking_Member_List) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_Update_Talking_Member_List");
static_assert(sizeof(WBP_VoiceChatMenu_C_Update_Talking_Member_List) == 0x000060, "Wrong size on WBP_VoiceChatMenu_C_Update_Talking_Member_List");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Talking_Member_List, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_VoiceChatMenu_C_Update_Talking_Member_List::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Talking_Member_List, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_VoiceChatMenu_C_Update_Talking_Member_List::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Talking_Member_List, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000008, "Member 'WBP_VoiceChatMenu_C_Update_Talking_Member_List::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Talking_Member_List, CallFunc_GetTalkingMemberNames_ReturnValue) == 0x000010, "Member 'WBP_VoiceChatMenu_C_Update_Talking_Member_List::CallFunc_GetTalkingMemberNames_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Talking_Member_List, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'WBP_VoiceChatMenu_C_Update_Talking_Member_List::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Talking_Member_List, CallFunc_Array_Get_Item) == 0x000028, "Member 'WBP_VoiceChatMenu_C_Update_Talking_Member_List::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Talking_Member_List, CallFunc_Conv_StringToText_ReturnValue) == 0x000038, "Member 'WBP_VoiceChatMenu_C_Update_Talking_Member_List::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Talking_Member_List, CallFunc_Array_Length_ReturnValue) == 0x000050, "Member 'WBP_VoiceChatMenu_C_Update_Talking_Member_List::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Talking_Member_List, CallFunc_Less_IntInt_ReturnValue) == 0x000054, "Member 'WBP_VoiceChatMenu_C_Update_Talking_Member_List::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Talking_Member_List, CallFunc_SpawnObject_ReturnValue) == 0x000058, "Member 'WBP_VoiceChatMenu_C_Update_Talking_Member_List::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.Update Muted Member List
// 0x0060 (0x0060 - 0x0000)
struct WBP_VoiceChatMenu_C_Update_Muted_Member_List final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UDebugMenuVoiceChat*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         CallFunc_GetMuteMemberNames_ReturnValue;           // 0x0018(0x0010)(ReferenceParm)
	class UWBP_EntryItemMemberName_C*             CallFunc_SpawnObject_ReturnValue;                  // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Array_Get_Item;                           // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0040(0x0018)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_VoiceChatMenu_C_Update_Muted_Member_List) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_Update_Muted_Member_List");
static_assert(sizeof(WBP_VoiceChatMenu_C_Update_Muted_Member_List) == 0x000060, "Wrong size on WBP_VoiceChatMenu_C_Update_Muted_Member_List");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Muted_Member_List, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_VoiceChatMenu_C_Update_Muted_Member_List::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Muted_Member_List, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_VoiceChatMenu_C_Update_Muted_Member_List::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Muted_Member_List, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'WBP_VoiceChatMenu_C_Update_Muted_Member_List::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Muted_Member_List, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000010, "Member 'WBP_VoiceChatMenu_C_Update_Muted_Member_List::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Muted_Member_List, CallFunc_GetMuteMemberNames_ReturnValue) == 0x000018, "Member 'WBP_VoiceChatMenu_C_Update_Muted_Member_List::CallFunc_GetMuteMemberNames_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Muted_Member_List, CallFunc_SpawnObject_ReturnValue) == 0x000028, "Member 'WBP_VoiceChatMenu_C_Update_Muted_Member_List::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Muted_Member_List, CallFunc_Array_Get_Item) == 0x000030, "Member 'WBP_VoiceChatMenu_C_Update_Muted_Member_List::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Muted_Member_List, CallFunc_Conv_StringToText_ReturnValue) == 0x000040, "Member 'WBP_VoiceChatMenu_C_Update_Muted_Member_List::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Muted_Member_List, CallFunc_Array_Length_ReturnValue) == 0x000058, "Member 'WBP_VoiceChatMenu_C_Update_Muted_Member_List::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Muted_Member_List, CallFunc_Less_IntInt_ReturnValue) == 0x00005C, "Member 'WBP_VoiceChatMenu_C_Update_Muted_Member_List::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_VoiceChatMenu.WBP_VoiceChatMenu_C.Update Member Volume List
// 0x0060 (0x0060 - 0x0000)
struct WBP_VoiceChatMenu_C_Update_Member_Volume_List final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDebugMenuVoiceChat*                    CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         CallFunc_GetMemberVolumes_ReturnValue;             // 0x0010(0x0010)(ReferenceParm)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Array_Get_Item;                           // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0038(0x0018)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_EntryItemMemberName_C*             CallFunc_SpawnObject_ReturnValue;                  // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_VoiceChatMenu_C_Update_Member_Volume_List) == 0x000008, "Wrong alignment on WBP_VoiceChatMenu_C_Update_Member_Volume_List");
static_assert(sizeof(WBP_VoiceChatMenu_C_Update_Member_Volume_List) == 0x000060, "Wrong size on WBP_VoiceChatMenu_C_Update_Member_Volume_List");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Member_Volume_List, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_VoiceChatMenu_C_Update_Member_Volume_List::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Member_Volume_List, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_VoiceChatMenu_C_Update_Member_Volume_List::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Member_Volume_List, CallFunc_GetLocalPlayerSubsystem_ReturnValue) == 0x000008, "Member 'WBP_VoiceChatMenu_C_Update_Member_Volume_List::CallFunc_GetLocalPlayerSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Member_Volume_List, CallFunc_GetMemberVolumes_ReturnValue) == 0x000010, "Member 'WBP_VoiceChatMenu_C_Update_Member_Volume_List::CallFunc_GetMemberVolumes_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Member_Volume_List, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'WBP_VoiceChatMenu_C_Update_Member_Volume_List::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Member_Volume_List, CallFunc_Array_Get_Item) == 0x000028, "Member 'WBP_VoiceChatMenu_C_Update_Member_Volume_List::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Member_Volume_List, CallFunc_Conv_StringToText_ReturnValue) == 0x000038, "Member 'WBP_VoiceChatMenu_C_Update_Member_Volume_List::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Member_Volume_List, CallFunc_Array_Length_ReturnValue) == 0x000050, "Member 'WBP_VoiceChatMenu_C_Update_Member_Volume_List::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Member_Volume_List, CallFunc_Less_IntInt_ReturnValue) == 0x000054, "Member 'WBP_VoiceChatMenu_C_Update_Member_Volume_List::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_VoiceChatMenu_C_Update_Member_Volume_List, CallFunc_SpawnObject_ReturnValue) == 0x000058, "Member 'WBP_VoiceChatMenu_C_Update_Member_Volume_List::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");

}

