#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ChatIcon

#include "Basic.hpp"

#include "WBP_ChatIcon_classes.hpp"
#include "WBP_ChatIcon_parameters.hpp"


namespace SDK
{

// Function WBP_ChatIcon.WBP_ChatIcon_C.ExecuteUbergraph_WBP_ChatIcon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChatIcon_C::ExecuteUbergraph_WBP_ChatIcon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatIcon_C", "ExecuteUbergraph_WBP_ChatIcon");

	Params::WBP_ChatIcon_C_ExecuteUbergraph_WBP_ChatIcon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatIcon.WBP_ChatIcon_C.OnAddToScreen
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ChatIcon_C::OnAddToScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatIcon_C", "OnAddToScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ChatIcon.WBP_ChatIcon_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ChatIcon_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatIcon_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ChatIcon.WBP_ChatIcon_C.OnAnimationFinished
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// const class UWidgetAnimation*           Animation                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ChatIcon_C::OnAnimationFinished(const class UWidgetAnimation* Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatIcon_C", "OnAnimationFinished");

	Params::WBP_ChatIcon_C_OnAnimationFinished Parms{};

	Parms.Animation = Animation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ChatIcon.WBP_ChatIcon_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ChatIcon_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ChatIcon_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

