#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CarValueOverlapper

#include "Basic.hpp"

#include "Money_base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CarValueOverlapper.BP_CarValueOverlapper_C
// 0x0008 (0x0270 - 0x0268)
class ABP_CarValueOverlapper_C final : public AMoney_base_C
{
public:
	class UBoxComponent*                          Box;                                               // 0x0268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CarValueOverlapper_C">();
	}
	static class ABP_CarValueOverlapper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CarValueOverlapper_C>();
	}
};
static_assert(alignof(ABP_CarValueOverlapper_C) == 0x000008, "Wrong alignment on ABP_CarValueOverlapper_C");
static_assert(sizeof(ABP_CarValueOverlapper_C) == 0x000270, "Wrong size on ABP_CarValueOverlapper_C");
static_assert(offsetof(ABP_CarValueOverlapper_C, Box) == 0x000268, "Member 'ABP_CarValueOverlapper_C::Box' has a wrong offset!");

}

