#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CateringDrinksCustomer

#include "Basic.hpp"

#include "CateringDrinksCustomer_classes.hpp"
#include "CateringDrinksCustomer_parameters.hpp"


namespace SDK
{

// Function CateringDrinksCustomer.CateringDrinksCustomer_C.ExecuteUbergraph_CateringDrinksCustomer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACateringDrinksCustomer_C::ExecuteUbergraph_CateringDrinksCustomer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "ExecuteUbergraph_CateringDrinksCustomer");

	Params::CateringDrinksCustomer_C_ExecuteUbergraph_CateringDrinksCustomer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.GetGlassDrinkReady
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ACateringDrinksCustomer_C::GetGlassDrinkReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "GetGlassDrinkReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.DrinkFromGlass
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ACateringDrinksCustomer_C::DrinkFromGlass()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "DrinkFromGlass");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.UpdateCustomerOutfits
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ACateringDrinksCustomer_C::UpdateCustomerOutfits()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "UpdateCustomerOutfits");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.SelectClothes
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ACateringDrinksCustomer_C::SelectClothes()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "SelectClothes");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.PhysAnim
// (BlueprintCallable, BlueprintEvent)

void ACateringDrinksCustomer_C::PhysAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "PhysAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.UpdateBubbleForOverlappers
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ACateringDrinksCustomer_C::UpdateBubbleForOverlappers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "UpdateBubbleForOverlappers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.ReceiveActorEndOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACateringDrinksCustomer_C::ReceiveActorEndOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "ReceiveActorEndOverlap");

	Params::CateringDrinksCustomer_C_ReceiveActorEndOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACateringDrinksCustomer_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "ReceiveActorBeginOverlap");

	Params::CateringDrinksCustomer_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.ServeCustomer
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACateringDrinksCustomer_C::ServeCustomer(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "ServeCustomer");

	Params::CateringDrinksCustomer_C_ServeCustomer Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.BndEvt__CateringCustomer_PlateOverlapper_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ACateringDrinksCustomer_C::BndEvt__CateringCustomer_PlateOverlapper_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "BndEvt__CateringCustomer_PlateOverlapper_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::CateringDrinksCustomer_C_BndEvt__CateringCustomer_PlateOverlapper_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.SetupCustomer
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ACateringDrinksCustomer_C::SetupCustomer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "SetupCustomer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ACateringDrinksCustomer_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ACateringDrinksCustomer_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.SpecifyCustomerOutfitAndAdd
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FCustomerOutfitStruct>&   OutfitArray                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FCustomerOutfitStruct*           OutfitOut                                              (Parm, OutParm, HasGetValueTypeHash)

void ACateringDrinksCustomer_C::SpecifyCustomerOutfitAndAdd(TArray<struct FCustomerOutfitStruct>& OutfitArray, struct FCustomerOutfitStruct* OutfitOut)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "SpecifyCustomerOutfitAndAdd");

	Params::CateringDrinksCustomer_C_SpecifyCustomerOutfitAndAdd Parms{};

	Parms.OutfitArray = std::move(OutfitArray);

	UObject::ProcessEvent(Func, &Parms);

	OutfitArray = std::move(Parms.OutfitArray);

	if (OutfitOut != nullptr)
		*OutfitOut = std::move(Parms.OutfitOut);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.SethairColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACateringDrinksCustomer_C::SethairColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "SethairColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.FoodToDrinkTranslator
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FMenuBPStruct&             Dish_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference, HasGetValueTypeHash)
// struct FDrinksOrderStruct*              Drinkrecipe                                            (Parm, OutParm, HasGetValueTypeHash)

void ACateringDrinksCustomer_C::FoodToDrinkTranslator(const struct FMenuBPStruct& Dish_0, struct FDrinksOrderStruct* Drinkrecipe)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "FoodToDrinkTranslator");

	Params::CateringDrinksCustomer_C_FoodToDrinkTranslator Parms{};

	Parms.Dish_0 = std::move(Dish_0);

	UObject::ProcessEvent(Func, &Parms);

	if (Drinkrecipe != nullptr)
		*Drinkrecipe = std::move(Parms.Drinkrecipe);
}


// Function CateringDrinksCustomer.CateringDrinksCustomer_C.DrinkToFoodTranslator
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FDrinksOrderStruct&        Drink                                                  (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// struct FMenuBPStruct*                   Food                                                   (Parm, OutParm, ContainsInstancedReference, HasGetValueTypeHash)

void ACateringDrinksCustomer_C::DrinkToFoodTranslator(const struct FDrinksOrderStruct& Drink, struct FMenuBPStruct* Food)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CateringDrinksCustomer_C", "DrinkToFoodTranslator");

	Params::CateringDrinksCustomer_C_DrinkToFoodTranslator Parms{};

	Parms.Drink = std::move(Drink);

	UObject::ProcessEvent(Func, &Parms);

	if (Food != nullptr)
		*Food = std::move(Parms.Food);
}

}

