#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ceiling

#include "Basic.hpp"

#include "Ceiling_classes.hpp"
#include "Ceiling_parameters.hpp"


namespace SDK
{

// Function Ceiling.Ceiling_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACeiling_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ceiling_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

