#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CookTop

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function CookTop.CookTop_C.ExecuteUbergraph_CookTop
// 0x0080 (0x0080 - 0x0000)
struct CookTop_C_ExecuteUbergraph_CookTop final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_OtherActor_1;                         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_CustomEvent_Actor_1;                        // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_OtherActor;                           // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACookableFoodBP_C*                      K2Node_DynamicCast_AsCookable_Food_BP;             // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_CustomEvent_Actor;                          // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACookableFoodBP_C*                      K2Node_DynamicCast_AsCookable_Food_BP_1;           // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_GetOverlappingActors_OverlappingActors;   // 0x0048(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x005D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5E[0x2];                                       // 0x005E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0060(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0070(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CookTop_C_ExecuteUbergraph_CookTop) == 0x000008, "Wrong alignment on CookTop_C_ExecuteUbergraph_CookTop");
static_assert(sizeof(CookTop_C_ExecuteUbergraph_CookTop) == 0x000080, "Wrong size on CookTop_C_ExecuteUbergraph_CookTop");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, EntryPoint) == 0x000000, "Member 'CookTop_C_ExecuteUbergraph_CookTop::EntryPoint' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, Temp_bool_IsClosed_Variable) == 0x000004, "Member 'CookTop_C_ExecuteUbergraph_CookTop::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, Temp_bool_Has_Been_Initd_Variable) == 0x000005, "Member 'CookTop_C_ExecuteUbergraph_CookTop::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, K2Node_Event_OtherActor_1) == 0x000008, "Member 'CookTop_C_ExecuteUbergraph_CookTop::K2Node_Event_OtherActor_1' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, K2Node_CustomEvent_Actor_1) == 0x000010, "Member 'CookTop_C_ExecuteUbergraph_CookTop::K2Node_CustomEvent_Actor_1' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, K2Node_Event_OtherActor) == 0x000018, "Member 'CookTop_C_ExecuteUbergraph_CookTop::K2Node_Event_OtherActor' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, K2Node_DynamicCast_AsCookable_Food_BP) == 0x000020, "Member 'CookTop_C_ExecuteUbergraph_CookTop::K2Node_DynamicCast_AsCookable_Food_BP' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'CookTop_C_ExecuteUbergraph_CookTop::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, K2Node_CustomEvent_Actor) == 0x000030, "Member 'CookTop_C_ExecuteUbergraph_CookTop::K2Node_CustomEvent_Actor' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, K2Node_DynamicCast_AsCookable_Food_BP_1) == 0x000038, "Member 'CookTop_C_ExecuteUbergraph_CookTop::K2Node_DynamicCast_AsCookable_Food_BP_1' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, K2Node_DynamicCast_bSuccess_1) == 0x000040, "Member 'CookTop_C_ExecuteUbergraph_CookTop::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, CallFunc_GetOverlappingActors_OverlappingActors) == 0x000048, "Member 'CookTop_C_ExecuteUbergraph_CookTop::CallFunc_GetOverlappingActors_OverlappingActors' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, CallFunc_Array_Length_ReturnValue) == 0x000058, "Member 'CookTop_C_ExecuteUbergraph_CookTop::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, CallFunc_Greater_IntInt_ReturnValue) == 0x00005C, "Member 'CookTop_C_ExecuteUbergraph_CookTop::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, Temp_bool_IsClosed_Variable_1) == 0x00005D, "Member 'CookTop_C_ExecuteUbergraph_CookTop::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000060, "Member 'CookTop_C_ExecuteUbergraph_CookTop::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, Temp_bool_Has_Been_Initd_Variable_1) == 0x00006C, "Member 'CookTop_C_ExecuteUbergraph_CookTop::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(CookTop_C_ExecuteUbergraph_CookTop, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000070, "Member 'CookTop_C_ExecuteUbergraph_CookTop::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");

// Function CookTop.CookTop_C.StopOverlapOven
// 0x0008 (0x0008 - 0x0000)
struct CookTop_C_StopOverlapOven final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CookTop_C_StopOverlapOven) == 0x000008, "Wrong alignment on CookTop_C_StopOverlapOven");
static_assert(sizeof(CookTop_C_StopOverlapOven) == 0x000008, "Wrong size on CookTop_C_StopOverlapOven");
static_assert(offsetof(CookTop_C_StopOverlapOven, Actor) == 0x000000, "Member 'CookTop_C_StopOverlapOven::Actor' has a wrong offset!");

// Function CookTop.CookTop_C.ReceiveActorEndOverlap
// 0x0008 (0x0008 - 0x0000)
struct CookTop_C_ReceiveActorEndOverlap final
{
public:
	class AActor*                                 OtherActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CookTop_C_ReceiveActorEndOverlap) == 0x000008, "Wrong alignment on CookTop_C_ReceiveActorEndOverlap");
static_assert(sizeof(CookTop_C_ReceiveActorEndOverlap) == 0x000008, "Wrong size on CookTop_C_ReceiveActorEndOverlap");
static_assert(offsetof(CookTop_C_ReceiveActorEndOverlap, OtherActor) == 0x000000, "Member 'CookTop_C_ReceiveActorEndOverlap::OtherActor' has a wrong offset!");

// Function CookTop.CookTop_C.OverlapOven
// 0x0008 (0x0008 - 0x0000)
struct CookTop_C_OverlapOven final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CookTop_C_OverlapOven) == 0x000008, "Wrong alignment on CookTop_C_OverlapOven");
static_assert(sizeof(CookTop_C_OverlapOven) == 0x000008, "Wrong size on CookTop_C_OverlapOven");
static_assert(offsetof(CookTop_C_OverlapOven, Actor) == 0x000000, "Member 'CookTop_C_OverlapOven::Actor' has a wrong offset!");

// Function CookTop.CookTop_C.ReceiveActorBeginOverlap
// 0x0008 (0x0008 - 0x0000)
struct CookTop_C_ReceiveActorBeginOverlap final
{
public:
	class AActor*                                 OtherActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CookTop_C_ReceiveActorBeginOverlap) == 0x000008, "Wrong alignment on CookTop_C_ReceiveActorBeginOverlap");
static_assert(sizeof(CookTop_C_ReceiveActorBeginOverlap) == 0x000008, "Wrong size on CookTop_C_ReceiveActorBeginOverlap");
static_assert(offsetof(CookTop_C_ReceiveActorBeginOverlap, OtherActor) == 0x000000, "Member 'CookTop_C_ReceiveActorBeginOverlap::OtherActor' has a wrong offset!");

}

