#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CostumerReviews

#include "Basic.hpp"

#include "CostumerReviews_classes.hpp"
#include "CostumerReviews_parameters.hpp"


namespace SDK
{

// Function CostumerReviews.CostumerReviews_C.ExecuteUbergraph_CostumerReviews
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACostumerReviews_C::ExecuteUbergraph_CostumerReviews(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CostumerReviews_C", "ExecuteUbergraph_CostumerReviews");

	Params::CostumerReviews_C_ExecuteUbergraph_CostumerReviews Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CostumerReviews.CostumerReviews_C.UpdateReviews
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ACostumerReviews_C::UpdateReviews()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CostumerReviews_C", "UpdateReviews");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CostumerReviews.CostumerReviews_C.Add review
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Review                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FString&                    Comment                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ACostumerReviews_C::Add_review(float Review, const class FString& Comment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CostumerReviews_C", "Add review");

	Params::CostumerReviews_C_Add_review Parms{};

	Parms.Review = Review;
	Parms.Comment = std::move(Comment);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CostumerReviews.CostumerReviews_C.SmileyDetermine
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Review                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture2D**                      Smiley                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACostumerReviews_C::SmileyDetermine(float Review, class UTexture2D** Smiley)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CostumerReviews_C", "SmileyDetermine");

	Params::CostumerReviews_C_SmileyDetermine Parms{};

	Parms.Review = Review;

	UObject::ProcessEvent(Func, &Parms);

	if (Smiley != nullptr)
		*Smiley = Parms.Smiley;
}

}

