#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DefaultPlayerAnimBP

#include "Basic.hpp"

#include "DefaultPlayerAnimBP_classes.hpp"
#include "DefaultPlayerAnimBP_parameters.hpp"


namespace SDK
{

// Function DefaultPlayerAnimBP.DefaultPlayerAnimBP_C.ExecuteUbergraph_DefaultPlayerAnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDefaultPlayerAnimBP_C::ExecuteUbergraph_DefaultPlayerAnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultPlayerAnimBP_C", "ExecuteUbergraph_DefaultPlayerAnimBP");

	Params::DefaultPlayerAnimBP_C_ExecuteUbergraph_DefaultPlayerAnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DefaultPlayerAnimBP.DefaultPlayerAnimBP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDefaultPlayerAnimBP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultPlayerAnimBP_C", "BlueprintUpdateAnimation");

	Params::DefaultPlayerAnimBP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DefaultPlayerAnimBP.DefaultPlayerAnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_TransitionResult_97940292492939F17CF8C39416D38E19
// (BlueprintEvent)

void UDefaultPlayerAnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_TransitionResult_97940292492939F17CF8C39416D38E19()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultPlayerAnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_TransitionResult_97940292492939F17CF8C39416D38E19");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DefaultPlayerAnimBP.DefaultPlayerAnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_BlendSpacePlayer_AE45DC414D5FC64AD7299EB3C972305C
// (BlueprintEvent)

void UDefaultPlayerAnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_BlendSpacePlayer_AE45DC414D5FC64AD7299EB3C972305C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultPlayerAnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_BlendSpacePlayer_AE45DC414D5FC64AD7299EB3C972305C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DefaultPlayerAnimBP.DefaultPlayerAnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_A0E68FF44F420BBB9CD6A68E5B398D32
// (BlueprintEvent)

void UDefaultPlayerAnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_A0E68FF44F420BBB9CD6A68E5B398D32()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultPlayerAnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_A0E68FF44F420BBB9CD6A68E5B398D32");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DefaultPlayerAnimBP.DefaultPlayerAnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_331D2AAC43FB8C915A6073A30B6005B1
// (BlueprintEvent)

void UDefaultPlayerAnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_331D2AAC43FB8C915A6073A30B6005B1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultPlayerAnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_331D2AAC43FB8C915A6073A30B6005B1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DefaultPlayerAnimBP.DefaultPlayerAnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_64AD4E99469FAD50A7047282352E32E8
// (BlueprintEvent)

void UDefaultPlayerAnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_64AD4E99469FAD50A7047282352E32E8()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultPlayerAnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_64AD4E99469FAD50A7047282352E32E8");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DefaultPlayerAnimBP.DefaultPlayerAnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_197CFE9E4E2EF52ED73133BC58897C9B
// (BlueprintEvent)

void UDefaultPlayerAnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_197CFE9E4E2EF52ED73133BC58897C9B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultPlayerAnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_ModifyBone_197CFE9E4E2EF52ED73133BC58897C9B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DefaultPlayerAnimBP.DefaultPlayerAnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_TransitionResult_3426C01D43A051A361FF3490FFCB714A
// (BlueprintEvent)

void UDefaultPlayerAnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_TransitionResult_3426C01D43A051A361FF3490FFCB714A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultPlayerAnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_DefaultPlayerAnimBP_AnimGraphNode_TransitionResult_3426C01D43A051A361FF3490FFCB714A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DefaultPlayerAnimBP.DefaultPlayerAnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UDefaultPlayerAnimBP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DefaultPlayerAnimBP_C", "AnimGraph");

	Params::DefaultPlayerAnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

