#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DrinksCustomerSpawner

#include "Basic.hpp"

#include "DrinksCustomerSpawner_classes.hpp"
#include "DrinksCustomerSpawner_parameters.hpp"


namespace SDK
{

// Function DrinksCustomerSpawner.DrinksCustomerSpawner_C.ExecuteUbergraph_DrinksCustomerSpawner
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADrinksCustomerSpawner_C::ExecuteUbergraph_DrinksCustomerSpawner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DrinksCustomerSpawner_C", "ExecuteUbergraph_DrinksCustomerSpawner");

	Params::DrinksCustomerSpawner_C_ExecuteUbergraph_DrinksCustomerSpawner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DrinksCustomerSpawner.DrinksCustomerSpawner_C.SpawnCustomer
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ADrinksCustomerSpawner_C::SpawnCustomer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DrinksCustomerSpawner_C", "SpawnCustomer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DrinksCustomerSpawner.DrinksCustomerSpawner_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ADrinksCustomerSpawner_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DrinksCustomerSpawner_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

