#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DrinksServingCrate

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DrinksServingCrate.DrinksServingCrate_C
// 0x0068 (0x0288 - 0x0220)
class ADrinksServingCrate_C : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPickupitemComp_C*                      PickupitemComp;                                    // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          CrateOverlapper;                                   // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        AttachLocation;                                    // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ULookatInfoComponent_C*                 LookatInfoComponent;                               // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USmoothSync*                            SmoothSync;                                        // 0x0248(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 ActorToSpawn;                                      // 0x0258(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TArray<class AActor*>                         overlappingAcors;                                  // 0x0260(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class UClass*>                         BottleActors;                                      // 0x0270(0x0010)(Edit, BlueprintVisible, Net, ExposeOnSpawn)
	bool                                          Bundles_;                                          // 0x0280(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_DrinksServingCrate(int32 EntryPoint);
	void BndEvt__DrinksServingCrate_PickupitemComp_K2Node_ComponentBoundEvent_0_PickupItem__DelegateSignature(class APlayerCharacter_C* Player);
	void Remove_overlapper(class AActor* Actor);
	void ReceiveActorEndOverlap(class AActor* OtherActor);
	void AddOverlapper(class AActor* Actor);
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void AttachAll();
	void SpawnActorOnArrows();
	void ReceiveBeginPlay();
	void SpawnActors(TArray<class AActor*>* Actors_spawned);
	void SpawnActorsBasedOnOrder(TArray<class AActor*>* SpawnedActors);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DrinksServingCrate_C">();
	}
	static class ADrinksServingCrate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADrinksServingCrate_C>();
	}
};
static_assert(alignof(ADrinksServingCrate_C) == 0x000008, "Wrong alignment on ADrinksServingCrate_C");
static_assert(sizeof(ADrinksServingCrate_C) == 0x000288, "Wrong size on ADrinksServingCrate_C");
static_assert(offsetof(ADrinksServingCrate_C, UberGraphFrame) == 0x000220, "Member 'ADrinksServingCrate_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ADrinksServingCrate_C, PickupitemComp) == 0x000228, "Member 'ADrinksServingCrate_C::PickupitemComp' has a wrong offset!");
static_assert(offsetof(ADrinksServingCrate_C, CrateOverlapper) == 0x000230, "Member 'ADrinksServingCrate_C::CrateOverlapper' has a wrong offset!");
static_assert(offsetof(ADrinksServingCrate_C, AttachLocation) == 0x000238, "Member 'ADrinksServingCrate_C::AttachLocation' has a wrong offset!");
static_assert(offsetof(ADrinksServingCrate_C, LookatInfoComponent) == 0x000240, "Member 'ADrinksServingCrate_C::LookatInfoComponent' has a wrong offset!");
static_assert(offsetof(ADrinksServingCrate_C, SmoothSync) == 0x000248, "Member 'ADrinksServingCrate_C::SmoothSync' has a wrong offset!");
static_assert(offsetof(ADrinksServingCrate_C, StaticMesh) == 0x000250, "Member 'ADrinksServingCrate_C::StaticMesh' has a wrong offset!");
static_assert(offsetof(ADrinksServingCrate_C, ActorToSpawn) == 0x000258, "Member 'ADrinksServingCrate_C::ActorToSpawn' has a wrong offset!");
static_assert(offsetof(ADrinksServingCrate_C, overlappingAcors) == 0x000260, "Member 'ADrinksServingCrate_C::overlappingAcors' has a wrong offset!");
static_assert(offsetof(ADrinksServingCrate_C, BottleActors) == 0x000270, "Member 'ADrinksServingCrate_C::BottleActors' has a wrong offset!");
static_assert(offsetof(ADrinksServingCrate_C, Bundles_) == 0x000280, "Member 'ADrinksServingCrate_C::Bundles_' has a wrong offset!");

}

