#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DrinksCustomerAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function DrinksCustomerAnimBP.DrinksCustomerAnimBP_C.ExecuteUbergraph_DrinksCustomerAnimBP
// 0x0070 (0x0070 - 0x0000)
struct DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaTimeX;                           // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetPlayLength_ReturnValue;                // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ADrinksCustomer_C*                      K2Node_DynamicCast_AsDrinks_Customer;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetActorForwardVector_ReturnValue;        // 0x002C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetVelocity_ReturnValue;                  // 0x0038(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Dot_VectorVector_ReturnValue;             // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A[0x6];                                       // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UAnimSequenceBase*>              K2Node_MakeArray_Array;                            // 0x0050(0x0010)(ConstParm, ReferenceParm)
	class UAnimSequenceBase*                      CallFunc_Array_Random_OutItem;                     // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Random_OutIndex;                    // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP) == 0x000008, "Wrong alignment on DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP");
static_assert(sizeof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP) == 0x000070, "Wrong size on DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, EntryPoint) == 0x000000, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::EntryPoint' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, K2Node_Event_DeltaTimeX) == 0x000004, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::K2Node_Event_DeltaTimeX' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, CallFunc_GetPlayLength_ReturnValue) == 0x000008, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::CallFunc_GetPlayLength_ReturnValue' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, CallFunc_TryGetPawnOwner_ReturnValue) == 0x000010, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::CallFunc_TryGetPawnOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, CallFunc_RandomFloatInRange_ReturnValue) == 0x000018, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, K2Node_DynamicCast_AsDrinks_Customer) == 0x000020, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::K2Node_DynamicCast_AsDrinks_Customer' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, CallFunc_GetActorForwardVector_ReturnValue) == 0x00002C, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::CallFunc_GetActorForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, CallFunc_GetVelocity_ReturnValue) == 0x000038, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::CallFunc_GetVelocity_ReturnValue' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, CallFunc_Dot_VectorVector_ReturnValue) == 0x000044, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::CallFunc_Dot_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, Temp_bool_Has_Been_Initd_Variable) == 0x000048, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, Temp_bool_IsClosed_Variable) == 0x000049, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, K2Node_MakeArray_Array) == 0x000050, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, CallFunc_Array_Random_OutItem) == 0x000060, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::CallFunc_Array_Random_OutItem' has a wrong offset!");
static_assert(offsetof(DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP, CallFunc_Array_Random_OutIndex) == 0x000068, "Member 'DrinksCustomerAnimBP_C_ExecuteUbergraph_DrinksCustomerAnimBP::CallFunc_Array_Random_OutIndex' has a wrong offset!");

// Function DrinksCustomerAnimBP.DrinksCustomerAnimBP_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct DrinksCustomerAnimBP_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DrinksCustomerAnimBP_C_BlueprintUpdateAnimation) == 0x000004, "Wrong alignment on DrinksCustomerAnimBP_C_BlueprintUpdateAnimation");
static_assert(sizeof(DrinksCustomerAnimBP_C_BlueprintUpdateAnimation) == 0x000004, "Wrong size on DrinksCustomerAnimBP_C_BlueprintUpdateAnimation");
static_assert(offsetof(DrinksCustomerAnimBP_C_BlueprintUpdateAnimation, DeltaTimeX) == 0x000000, "Member 'DrinksCustomerAnimBP_C_BlueprintUpdateAnimation::DeltaTimeX' has a wrong offset!");

// Function DrinksCustomerAnimBP.DrinksCustomerAnimBP_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct DrinksCustomerAnimBP_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(DrinksCustomerAnimBP_C_AnimGraph) == 0x000008, "Wrong alignment on DrinksCustomerAnimBP_C_AnimGraph");
static_assert(sizeof(DrinksCustomerAnimBP_C_AnimGraph) == 0x000010, "Wrong size on DrinksCustomerAnimBP_C_AnimGraph");
static_assert(offsetof(DrinksCustomerAnimBP_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'DrinksCustomerAnimBP_C_AnimGraph::AnimGraph_0' has a wrong offset!");

}

