#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EquipmentSkinChild

#include "Basic.hpp"

#include "EquipmentSkinChild_classes.hpp"
#include "EquipmentSkinChild_parameters.hpp"


namespace SDK
{

// Function EquipmentSkinChild.EquipmentSkinChild_C.ExecuteUbergraph_EquipmentSkinChild
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UEquipmentSkinChild_C::ExecuteUbergraph_EquipmentSkinChild(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EquipmentSkinChild_C", "ExecuteUbergraph_EquipmentSkinChild");

	Params::EquipmentSkinChild_C_ExecuteUbergraph_EquipmentSkinChild Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EquipmentSkinChild.EquipmentSkinChild_C.BndEvt__EquipmentSkinChild_Button_88_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UEquipmentSkinChild_C::BndEvt__EquipmentSkinChild_Button_88_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EquipmentSkinChild_C", "BndEvt__EquipmentSkinChild_Button_88_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EquipmentSkinChild.EquipmentSkinChild_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UEquipmentSkinChild_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EquipmentSkinChild_C", "GetVisibility_0");

	Params::EquipmentSkinChild_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function EquipmentSkinChild.EquipmentSkinChild_C.GetBrush_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UEquipmentSkinChild_C::GetBrush_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EquipmentSkinChild_C", "GetBrush_0");

	Params::EquipmentSkinChild_C_GetBrush_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function EquipmentSkinChild.EquipmentSkinChild_C.Get_MatBorder_Background_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UEquipmentSkinChild_C::Get_MatBorder_Background_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EquipmentSkinChild_C", "Get_MatBorder_Background_0");

	Params::EquipmentSkinChild_C_Get_MatBorder_Background_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

