#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FireSpread

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FireSpread.FireSpread_C
// 0x0028 (0x0248 - 0x0220)
class AFireSpread_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Box;                                               // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               ParticleSystem;                                    // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          Out;                                               // 0x0240(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_FireSpread(int32 EntryPoint);
	void CheckCanSpawn();
	void BndEvt__FireSpread_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void Spread();
	void Extingush();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FireSpread_C">();
	}
	static class AFireSpread_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFireSpread_C>();
	}
};
static_assert(alignof(AFireSpread_C) == 0x000008, "Wrong alignment on AFireSpread_C");
static_assert(sizeof(AFireSpread_C) == 0x000248, "Wrong size on AFireSpread_C");
static_assert(offsetof(AFireSpread_C, UberGraphFrame) == 0x000220, "Member 'AFireSpread_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AFireSpread_C, Box) == 0x000228, "Member 'AFireSpread_C::Box' has a wrong offset!");
static_assert(offsetof(AFireSpread_C, ParticleSystem) == 0x000230, "Member 'AFireSpread_C::ParticleSystem' has a wrong offset!");
static_assert(offsetof(AFireSpread_C, DefaultSceneRoot) == 0x000238, "Member 'AFireSpread_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(AFireSpread_C, Out) == 0x000240, "Member 'AFireSpread_C::Out' has a wrong offset!");

}

