#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FoodTruckTruck

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FoodTruckTruck.FoodTruckTruck_C
// 0x00E0 (0x0300 - 0x0220)
class AFoodTruckTruck_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   DeliveryHat;                                       // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 DeliveryCharacter_rigged;                          // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box6;                                              // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        TruckIdle;                                         // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Overlapper;                                        // 0x0248(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Arrow;                                             // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box5;                                              // 0x0258(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   DoorLeft;                                          // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   DoorRight;                                         // 0x0268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box4;                                              // 0x0270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box3;                                              // 0x0278(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box2;                                              // 0x0280(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box1;                                              // 0x0288(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x0290(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPoseableMeshComponent*                 PoseableMesh;                                      // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_NewTrack_0_D12C6B0D4CB732AF319E1B89C896CA4E; // 0x02A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_D12C6B0D4CB732AF319E1B89C896CA4E; // 0x02AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2AD[0x3];                                      // 0x02AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DriveBack_Alpha_40DE721E471B437A7707ACB58E62AFDC;  // 0x02B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            DriveBack__Direction_40DE721E471B437A7707ACB58E62AFDC; // 0x02BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BD[0x3];                                      // 0x02BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     DriveBack;                                         // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         OpenDoor_NewTrack_0_DC0B1C6F432FE4C7EA7355A77739663D; // 0x02C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            OpenDoor__Direction_DC0B1C6F432FE4C7EA7355A77739663D; // 0x02CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2CD[0x3];                                      // 0x02CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     OpenDoor;                                          // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MoveTruckTimeline_Alpha_A2CA33D947B66C942D572F93494B5B22; // 0x02D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            MoveTruckTimeline__Direction_A2CA33D947B66C942D572F93494B5B22; // 0x02DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2DD[0x3];                                      // 0x02DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     MoveTruckTimeline;                                 // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Alpha;                                             // 0x02E8(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2EC[0x4];                                      // 0x02EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AFoodTruckSpline_C*                     Track;                                             // 0x02F0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         Duration;                                          // 0x02F8(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          Parked_;                                           // 0x02FC(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_FoodTruckTruck(int32 EntryPoint);
	void SetParked();
	void DriveSound();
	void HornSound();
	void CloseDoors();
	void truckLeave();
	void EndOverlap(class AActor* Object);
	void BndEvt__FoodTruckTruck_Overlapper_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void Opentruck();
	void MovetruckDeliver(const TArray<struct FOrderFoodBPStruct>& Order);
	void Timeline_0__UpdateFunc();
	void Timeline_0__FinishedFunc();
	void DriveBack__UpdateFunc();
	void DriveBack__FinishedFunc();
	void OpenDoor__UpdateFunc();
	void OpenDoor__FinishedFunc();
	void MoveTruckTimeline__UpdateFunc();
	void MoveTruckTimeline__FinishedFunc();
	void SpawnFood();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FoodTruckTruck_C">();
	}
	static class AFoodTruckTruck_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFoodTruckTruck_C>();
	}
};
static_assert(alignof(AFoodTruckTruck_C) == 0x000008, "Wrong alignment on AFoodTruckTruck_C");
static_assert(sizeof(AFoodTruckTruck_C) == 0x000300, "Wrong size on AFoodTruckTruck_C");
static_assert(offsetof(AFoodTruckTruck_C, UberGraphFrame) == 0x000220, "Member 'AFoodTruckTruck_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, DeliveryHat) == 0x000228, "Member 'AFoodTruckTruck_C::DeliveryHat' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, DeliveryCharacter_rigged) == 0x000230, "Member 'AFoodTruckTruck_C::DeliveryCharacter_rigged' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Box6) == 0x000238, "Member 'AFoodTruckTruck_C::Box6' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, TruckIdle) == 0x000240, "Member 'AFoodTruckTruck_C::TruckIdle' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Overlapper) == 0x000248, "Member 'AFoodTruckTruck_C::Overlapper' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Arrow) == 0x000250, "Member 'AFoodTruckTruck_C::Arrow' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Box5) == 0x000258, "Member 'AFoodTruckTruck_C::Box5' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, DoorLeft) == 0x000260, "Member 'AFoodTruckTruck_C::DoorLeft' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, DoorRight) == 0x000268, "Member 'AFoodTruckTruck_C::DoorRight' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Box4) == 0x000270, "Member 'AFoodTruckTruck_C::Box4' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Box3) == 0x000278, "Member 'AFoodTruckTruck_C::Box3' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Box2) == 0x000280, "Member 'AFoodTruckTruck_C::Box2' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Box1) == 0x000288, "Member 'AFoodTruckTruck_C::Box1' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Box) == 0x000290, "Member 'AFoodTruckTruck_C::Box' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, PoseableMesh) == 0x000298, "Member 'AFoodTruckTruck_C::PoseableMesh' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, DefaultSceneRoot) == 0x0002A0, "Member 'AFoodTruckTruck_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Timeline_0_NewTrack_0_D12C6B0D4CB732AF319E1B89C896CA4E) == 0x0002A8, "Member 'AFoodTruckTruck_C::Timeline_0_NewTrack_0_D12C6B0D4CB732AF319E1B89C896CA4E' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Timeline_0__Direction_D12C6B0D4CB732AF319E1B89C896CA4E) == 0x0002AC, "Member 'AFoodTruckTruck_C::Timeline_0__Direction_D12C6B0D4CB732AF319E1B89C896CA4E' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Timeline_0) == 0x0002B0, "Member 'AFoodTruckTruck_C::Timeline_0' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, DriveBack_Alpha_40DE721E471B437A7707ACB58E62AFDC) == 0x0002B8, "Member 'AFoodTruckTruck_C::DriveBack_Alpha_40DE721E471B437A7707ACB58E62AFDC' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, DriveBack__Direction_40DE721E471B437A7707ACB58E62AFDC) == 0x0002BC, "Member 'AFoodTruckTruck_C::DriveBack__Direction_40DE721E471B437A7707ACB58E62AFDC' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, DriveBack) == 0x0002C0, "Member 'AFoodTruckTruck_C::DriveBack' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, OpenDoor_NewTrack_0_DC0B1C6F432FE4C7EA7355A77739663D) == 0x0002C8, "Member 'AFoodTruckTruck_C::OpenDoor_NewTrack_0_DC0B1C6F432FE4C7EA7355A77739663D' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, OpenDoor__Direction_DC0B1C6F432FE4C7EA7355A77739663D) == 0x0002CC, "Member 'AFoodTruckTruck_C::OpenDoor__Direction_DC0B1C6F432FE4C7EA7355A77739663D' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, OpenDoor) == 0x0002D0, "Member 'AFoodTruckTruck_C::OpenDoor' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, MoveTruckTimeline_Alpha_A2CA33D947B66C942D572F93494B5B22) == 0x0002D8, "Member 'AFoodTruckTruck_C::MoveTruckTimeline_Alpha_A2CA33D947B66C942D572F93494B5B22' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, MoveTruckTimeline__Direction_A2CA33D947B66C942D572F93494B5B22) == 0x0002DC, "Member 'AFoodTruckTruck_C::MoveTruckTimeline__Direction_A2CA33D947B66C942D572F93494B5B22' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, MoveTruckTimeline) == 0x0002E0, "Member 'AFoodTruckTruck_C::MoveTruckTimeline' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Alpha) == 0x0002E8, "Member 'AFoodTruckTruck_C::Alpha' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Track) == 0x0002F0, "Member 'AFoodTruckTruck_C::Track' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Duration) == 0x0002F8, "Member 'AFoodTruckTruck_C::Duration' has a wrong offset!");
static_assert(offsetof(AFoodTruckTruck_C, Parked_) == 0x0002FC, "Member 'AFoodTruckTruck_C::Parked_' has a wrong offset!");

}

