#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Foodtray

#include "Basic.hpp"

#include "Foodtray_classes.hpp"
#include "Foodtray_parameters.hpp"


namespace SDK
{

// Function Foodtray.Foodtray_C.ExecuteUbergraph_Foodtray
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFoodtray_C::ExecuteUbergraph_Foodtray(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Foodtray_C", "ExecuteUbergraph_Foodtray");

	Params::Foodtray_C_ExecuteUbergraph_Foodtray Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Foodtray.Foodtray_C.BndEvt__Foodtray_PickupitemComp_K2Node_ComponentBoundEvent_0_PickupItem__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class APlayerCharacter_C*               Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFoodtray_C::BndEvt__Foodtray_PickupitemComp_K2Node_ComponentBoundEvent_0_PickupItem__DelegateSignature(class APlayerCharacter_C* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Foodtray_C", "BndEvt__Foodtray_PickupitemComp_K2Node_ComponentBoundEvent_0_PickupItem__DelegateSignature");

	Params::Foodtray_C_BndEvt__Foodtray_PickupitemComp_K2Node_ComponentBoundEvent_0_PickupItem__DelegateSignature Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Foodtray.Foodtray_C.DetachAllitems
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void AFoodtray_C::DetachAllitems()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Foodtray_C", "DetachAllitems");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Foodtray.Foodtray_C.ReceiveActorEndOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFoodtray_C::ReceiveActorEndOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Foodtray_C", "ReceiveActorEndOverlap");

	Params::Foodtray_C_ReceiveActorEndOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Foodtray.Foodtray_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFoodtray_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Foodtray_C", "ReceiveActorBeginOverlap");

	Params::Foodtray_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Foodtray.Foodtray_C.AttachAllItems
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerCharacter_C*               Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFoodtray_C::AttachAllItems(class APlayerCharacter_C* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Foodtray_C", "AttachAllItems");

	Params::Foodtray_C_AttachAllItems Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Foodtray.Foodtray_C.RemoveOverlapper
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFoodtray_C::RemoveOverlapper(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Foodtray_C", "RemoveOverlapper");

	Params::Foodtray_C_RemoveOverlapper Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Foodtray.Foodtray_C.AddOverlapper
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFoodtray_C::AddOverlapper(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Foodtray_C", "AddOverlapper");

	Params::Foodtray_C_AddOverlapper Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}

}

