#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GamelengthStruct

#include "Basic.hpp"

#include "GamelengthEnum_structs.hpp"


namespace SDK
{

// UserDefinedStruct GamelengthStruct.GamelengthStruct
// 0x0008 (0x0008 - 0x0000)
struct FGamelengthStruct final
{
public:
	EGamelengthEnum                               LengthMode_2_F96EA14F40FD269312A8D7976D393A68;     // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MoneyMakeBase_5_AAA5CD3A4A1ADA823296989EC28CC884;  // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FGamelengthStruct) == 0x000004, "Wrong alignment on FGamelengthStruct");
static_assert(sizeof(FGamelengthStruct) == 0x000008, "Wrong size on FGamelengthStruct");
static_assert(offsetof(FGamelengthStruct, LengthMode_2_F96EA14F40FD269312A8D7976D393A68) == 0x000000, "Member 'FGamelengthStruct::LengthMode_2_F96EA14F40FD269312A8D7976D393A68' has a wrong offset!");
static_assert(offsetof(FGamelengthStruct, MoneyMakeBase_5_AAA5CD3A4A1ADA823296989EC28CC884) == 0x000004, "Member 'FGamelengthStruct::MoneyMakeBase_5_AAA5CD3A4A1ADA823296989EC28CC884' has a wrong offset!");

}

