#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HalfChickenBreast

#include "Basic.hpp"

#include "CutableFoodBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HalfChickenBreast.HalfChickenBreast_C
// 0x0000 (0x02D0 - 0x02D0)
class AHalfChickenBreast_C final : public ACutableFoodBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HalfChickenBreast_C">();
	}
	static class AHalfChickenBreast_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHalfChickenBreast_C>();
	}
};
static_assert(alignof(AHalfChickenBreast_C) == 0x000008, "Wrong alignment on AHalfChickenBreast_C");
static_assert(sizeof(AHalfChickenBreast_C) == 0x0002D0, "Wrong size on AHalfChickenBreast_C");

}

