#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MoneyManager

#include "Basic.hpp"

#include "MoneyManager_classes.hpp"
#include "MoneyManager_parameters.hpp"


namespace SDK
{

// Function MoneyManager.MoneyManager_C.ExecuteUbergraph_MoneyManager
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMoneyManager_C::ExecuteUbergraph_MoneyManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MoneyManager_C", "ExecuteUbergraph_MoneyManager");

	Params::MoneyManager_C_ExecuteUbergraph_MoneyManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MoneyManager.MoneyManager_C.InfiniteMoney
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void AMoneyManager_C::InfiniteMoney()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MoneyManager_C", "InfiniteMoney");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MoneyManager.MoneyManager_C.ChangeMoney
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Amount                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMoneyManager_C::ChangeMoney(int32 Amount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MoneyManager_C", "ChangeMoney");

	Params::MoneyManager_C_ChangeMoney Parms{};

	Parms.Amount = Amount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MoneyManager.MoneyManager_C.Update money
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void AMoneyManager_C::Update_money()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MoneyManager_C", "Update money");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MoneyManager.MoneyManager_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AMoneyManager_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MoneyManager_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

