#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OceanOrderSpawner

#include "Basic.hpp"

#include "OrderFoodBPStruct_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function OceanOrderSpawner.OceanOrderSpawner_C.ExecuteUbergraph_OceanOrderSpawner
// 0x00C0 (0x00C0 - 0x0000)
struct OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FOrderFoodBPStruct>             K2Node_CustomEvent_Order;                          // 0x0010(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_LastIndex_ReturnValue;              // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOrderFoodBPStruct                     CallFunc_Array_Get_Item;                           // 0x0028(0x0028)(ZeroConstructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0050(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0060(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AOrderFoodBP_C*                         CallFunc_GetActorOfClass_ReturnValue;              // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x00A8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner) == 0x000010, "Wrong alignment on OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner");
static_assert(sizeof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner) == 0x0000C0, "Wrong size on OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, EntryPoint) == 0x000000, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::EntryPoint' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, Temp_int_Variable) == 0x000004, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, K2Node_CustomEvent_Order) == 0x000010, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::K2Node_CustomEvent_Order' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, CallFunc_Array_LastIndex_ReturnValue) == 0x000020, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::CallFunc_Array_LastIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000024, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, CallFunc_Array_Get_Item) == 0x000028, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000050, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, CallFunc_MakeTransform_ReturnValue) == 0x000060, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000090, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, CallFunc_FinishSpawningActor_ReturnValue) == 0x000098, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, CallFunc_GetActorOfClass_ReturnValue) == 0x0000A0, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::CallFunc_GetActorOfClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x0000A8, "Member 'OceanOrderSpawner_C_ExecuteUbergraph_OceanOrderSpawner::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");

// Function OceanOrderSpawner.OceanOrderSpawner_C.DeliverOcean
// 0x0010 (0x0010 - 0x0000)
struct OceanOrderSpawner_C_DeliverOcean final
{
public:
	TArray<struct FOrderFoodBPStruct>             Order_0;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(OceanOrderSpawner_C_DeliverOcean) == 0x000008, "Wrong alignment on OceanOrderSpawner_C_DeliverOcean");
static_assert(sizeof(OceanOrderSpawner_C_DeliverOcean) == 0x000010, "Wrong size on OceanOrderSpawner_C_DeliverOcean");
static_assert(offsetof(OceanOrderSpawner_C_DeliverOcean, Order_0) == 0x000000, "Member 'OceanOrderSpawner_C_DeliverOcean::Order_0' has a wrong offset!");

}

