#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PizzaStruct

#include "Basic.hpp"

#include "PizzaToppingStruct_structs.hpp"


namespace SDK
{

// UserDefinedStruct PizzaStruct.PizzaStruct
// 0x0020 (0x0020 - 0x0000)
struct FPizzaStruct final
{
public:
	bool                                          Sauce__1_86D288274E0B6D5A142F268DAF94AEC0;         // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FPizzaToppingStruct>            Toppings_5_1D675BC847B29DFF07D9018D019B5924;       // 0x0008(0x0010)(Edit, BlueprintVisible)
	int32                                         CookLevel_9_87E83262440EC797A20905AD35D21823;      // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FPizzaStruct) == 0x000008, "Wrong alignment on FPizzaStruct");
static_assert(sizeof(FPizzaStruct) == 0x000020, "Wrong size on FPizzaStruct");
static_assert(offsetof(FPizzaStruct, Sauce__1_86D288274E0B6D5A142F268DAF94AEC0) == 0x000000, "Member 'FPizzaStruct::Sauce__1_86D288274E0B6D5A142F268DAF94AEC0' has a wrong offset!");
static_assert(offsetof(FPizzaStruct, Toppings_5_1D675BC847B29DFF07D9018D019B5924) == 0x000008, "Member 'FPizzaStruct::Toppings_5_1D675BC847B29DFF07D9018D019B5924' has a wrong offset!");
static_assert(offsetof(FPizzaStruct, CookLevel_9_87E83262440EC797A20905AD35D21823) == 0x000018, "Member 'FPizzaStruct::CookLevel_9_87E83262440EC797A20905AD35D21823' has a wrong offset!");

}

