#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SettingsUI

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "SettingsStruct_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SettingsUI.SettingsUI_C
// 0x00E8 (0x0348 - 0x0260)
class USettingsUI_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton_default_C*                      Button_default_C_94;                               // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Controlsbutton;                                    // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                FOVSlider;                                         // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                FPSLeft;                                           // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                FPSRight;                                          // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        Graphics;                                          // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                HostGame;                                          // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                HostGame_1;                                        // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                MusicSlider;                                       // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                ResolutionScaleSlider;                             // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                SensSlider;                                        // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_0;                                       // 0x02C0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_3;                                       // 0x02C8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_10;                                      // 0x02D0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_12;                                      // 0x02D8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_14;                                      // 0x02E0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_205;                                     // 0x02E8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                VolumeSlider;                                      // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FSettingsStruct                        Settings;                                          // 0x02F8(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<class FString>                         FPSLimits;                                         // 0x0328(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FString                                 CurrentFPSLimit;                                   // 0x0338(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_SettingsUI(int32 EntryPoint);
	void BndEvt__SettingsUI_Button_default_C_94_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__SettingsUI_MusicSlider_K2Node_ComponentBoundEvent_10_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__SettingsUI_ResolutionScaleSlider_K2Node_ComponentBoundEvent_9_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void Construct();
	void BndEvt__SettingsUI_FOVSlider_K2Node_ComponentBoundEvent_8_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__SettingsUI_HostGame_1_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__SettingsUI_FPSLeft_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__SettingsUI_FPSRight_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__SettingsUI_Controlsbutton_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__SettingsUI_Graphics_K2Node_ComponentBoundEvent_4_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void BndEvt__SettingsUI_SensSlider_K2Node_ComponentBoundEvent_3_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__SettingsUI_HostGame_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__SettingsUI_VolumeSlider_K2Node_ComponentBoundEvent_1_OnFloatValueChangedEvent__DelegateSignature(float Value);
	class FText GetText_0();
	class FText GetText_1();
	class FText GetText_2();
	class FText GetText_3();
	class FText GetText_4();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SettingsUI_C">();
	}
	static class USettingsUI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USettingsUI_C>();
	}
};
static_assert(alignof(USettingsUI_C) == 0x000008, "Wrong alignment on USettingsUI_C");
static_assert(sizeof(USettingsUI_C) == 0x000348, "Wrong size on USettingsUI_C");
static_assert(offsetof(USettingsUI_C, UberGraphFrame) == 0x000260, "Member 'USettingsUI_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, Button_default_C_94) == 0x000268, "Member 'USettingsUI_C::Button_default_C_94' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, Controlsbutton) == 0x000270, "Member 'USettingsUI_C::Controlsbutton' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, FOVSlider) == 0x000278, "Member 'USettingsUI_C::FOVSlider' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, FPSLeft) == 0x000280, "Member 'USettingsUI_C::FPSLeft' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, FPSRight) == 0x000288, "Member 'USettingsUI_C::FPSRight' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, Graphics) == 0x000290, "Member 'USettingsUI_C::Graphics' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, HostGame) == 0x000298, "Member 'USettingsUI_C::HostGame' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, HostGame_1) == 0x0002A0, "Member 'USettingsUI_C::HostGame_1' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, MusicSlider) == 0x0002A8, "Member 'USettingsUI_C::MusicSlider' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, ResolutionScaleSlider) == 0x0002B0, "Member 'USettingsUI_C::ResolutionScaleSlider' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, SensSlider) == 0x0002B8, "Member 'USettingsUI_C::SensSlider' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, TextBlock_0) == 0x0002C0, "Member 'USettingsUI_C::TextBlock_0' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, TextBlock_3) == 0x0002C8, "Member 'USettingsUI_C::TextBlock_3' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, TextBlock_10) == 0x0002D0, "Member 'USettingsUI_C::TextBlock_10' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, TextBlock_12) == 0x0002D8, "Member 'USettingsUI_C::TextBlock_12' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, TextBlock_14) == 0x0002E0, "Member 'USettingsUI_C::TextBlock_14' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, TextBlock_205) == 0x0002E8, "Member 'USettingsUI_C::TextBlock_205' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, VolumeSlider) == 0x0002F0, "Member 'USettingsUI_C::VolumeSlider' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, Settings) == 0x0002F8, "Member 'USettingsUI_C::Settings' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, FPSLimits) == 0x000328, "Member 'USettingsUI_C::FPSLimits' has a wrong offset!");
static_assert(offsetof(USettingsUI_C, CurrentFPSLimit) == 0x000338, "Member 'USettingsUI_C::CurrentFPSLimit' has a wrong offset!");

}

