#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatTrackingComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StatTrackingComponent.StatTrackingComponent_C
// 0x0008 (0x00B8 - 0x00B0)
class UStatTrackingComponent_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_StatTrackingComponent(int32 EntryPoint);
	void TrackStat(class APlayerCharacter_C* Player, const struct FStatsStruct& Stat);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StatTrackingComponent_C">();
	}
	static class UStatTrackingComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStatTrackingComponent_C>();
	}
};
static_assert(alignof(UStatTrackingComponent_C) == 0x000008, "Wrong alignment on UStatTrackingComponent_C");
static_assert(sizeof(UStatTrackingComponent_C) == 0x0000B8, "Wrong size on UStatTrackingComponent_C");
static_assert(offsetof(UStatTrackingComponent_C, UberGraphFrame) == 0x0000B0, "Member 'UStatTrackingComponent_C::UberGraphFrame' has a wrong offset!");

}

