#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TrashComponent

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TrashComponent.TrashComponent_C
// 0x0000 (0x00B0 - 0x00B0)
class UTrashComponent_C final : public UActorComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TrashComponent_C">();
	}
	static class UTrashComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTrashComponent_C>();
	}
};
static_assert(alignof(UTrashComponent_C) == 0x000008, "Wrong alignment on UTrashComponent_C");
static_assert(sizeof(UTrashComponent_C) == 0x0000B0, "Wrong size on UTrashComponent_C");

}

