#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UnlockItemWidget

#include "Basic.hpp"

#include "UnlockItemWidget_classes.hpp"
#include "UnlockItemWidget_parameters.hpp"


namespace SDK
{

// Function UnlockItemWidget.UnlockItemWidget_C.ExecuteUbergraph_UnlockItemWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUnlockItemWidget_C::ExecuteUbergraph_UnlockItemWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockItemWidget_C", "ExecuteUbergraph_UnlockItemWidget");

	Params::UnlockItemWidget_C_ExecuteUbergraph_UnlockItemWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UnlockItemWidget.UnlockItemWidget_C.BndEvt__UnlockItemWidget_MainMenuButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUnlockItemWidget_C::BndEvt__UnlockItemWidget_MainMenuButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockItemWidget_C", "BndEvt__UnlockItemWidget_MainMenuButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UnlockItemWidget.UnlockItemWidget_C.GetBrush_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UUnlockItemWidget_C::GetBrush_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UnlockItemWidget_C", "GetBrush_0");

	Params::UnlockItemWidget_C_GetBrush_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

